In [3]:
import os

# Must be set before importing PaddleOCR.
os.environ["PADDLE_PDX_MODEL_SOURCE"] = "BOS"

from paddleocr import PaddleOCR

ocr = PaddleOCR(
    lang="ur",
    device="cpu",
    use_doc_orientation_classify=False,
    use_doc_unwarping=False,
    use_textline_orientation=False,
)

print("OCR models downloaded and initialized successfully.")

# python -u test_ocr.py

c:\Users\ammar\OneDrive\Desktop\largelisaanmodel\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Creating model: ('PP-OCRv5_server_det', None, None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\ammar\.paddlex\official_models\PP-OCRv5_server_det`.
c:\Users\ammar\OneDrive\Desktop\largelisaanmodel\venv\Lib\site-packages\paddle\utils\cpp_extension\extension_utils.py:718: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
Creating model: ('arabic_PP-OCRv5_mobile_rec', None, None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\ammar\.paddlex\official_models\arabic_PP-OCRv5_mobile_rec`.

OCR models downloaded and initialized successfully.

In [4]:
result = ocr.predict("data\\page1.png")

for page in result:
    for line in page["rec_texts"]:
        print(line)

٧٨٦
مؤمنين ني جاعة اله سبحانه في خلقة
ما غوروفكركري ة هيشر ا اية في تلاوة نا
مَمَالَ الََلرحيَمِإِنَ
كرناركرين
في حَلَقِاَلسَمَوَتِ وَألْأَرضِ وَآختِلَفِ اَلّْلِ
لنَارَِ لُى الأَالَِ يَذكُنَ
الَ ِمَا وَعُدََى جُم وََكَرُونَ
في حَلقِلسَمَتِ َألأَرضِ رَنَاَاَقَ َذَا
طلَطَُا ُْحَتَك فَِنَاعَابَالَاِ
مثل ااية پزهي  اج تاسوع نادن ما
عاشوراء نا دن واسط تياري كرناراين سكلاي
كرجردن ما حسين يراخلقة باطل نزتي جالي
اهني جرغرض ييرتمام تالي اهنا واسط شهادة
اختيار كيدي، سون غرض؟كراسمانو زمين

In [5]:
from paddleocr import PaddleOCR

urdu_ocr = PaddleOCR(
    lang="ur",
    device="cpu",
    use_doc_orientation_classify=False,
    use_doc_unwarping=False,
    use_textline_orientation=False,
)

arabic_ocr = PaddleOCR(
    lang="ar",
    device="cpu",
    use_doc_orientation_classify=False,
    use_doc_unwarping=False,
    use_textline_orientation=False,
)

Creating model: ('PP-OCRv5_server_det', None, None)

Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\ammar\.paddlex\official_models\PP-OCRv5_server_det`.
Creating model: ('arabic_PP-OCRv5_mobile_rec', None, None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\ammar\.paddlex\official_models\arabic_PP-OCRv5_mobile_rec`.
Creating model: ('PP-OCRv5_server_det', None, None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\ammar\.paddlex\official_models\PP-OCRv5_server_det`.
Creating model: ('arabic_PP-OCRv5_mobile_rec', None, None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\ammar\.paddlex\official_models\arabic_PP-OCRv5_mobile_rec`.

In [6]:
urdu_result = urdu_ocr.predict("data/page1.png")
arabic_result = arabic_ocr.predict("data/page1.png")

In [7]:
for page in urdu_result:
    for line in page["rec_texts"]:
        print(line)

٧٨٦
مؤمنين ني جاعة اله سبحانه في خلقة
ما غوروفكركري ة هيشر ا اية في تلاوة نا
مَمَالَ الََلرحيَمِإِنَ
كرناركرين
في حَلَقِاَلسَمَوَتِ وَألْأَرضِ وَآختِلَفِ اَلّْلِ
لنَارَِ لُى الأَالَِ يَذكُنَ
الَ ِمَا وَعُدََى جُم وََكَرُونَ
في حَلقِلسَمَتِ َألأَرضِ رَنَاَاَقَ َذَا
طلَطَُا ُْحَتَك فَِنَاعَابَالَاِ
مثل ااية پزهي  اج تاسوع نادن ما
عاشوراء نا دن واسط تياري كرناراين سكلاي
كرجردن ما حسين يراخلقة باطل نزتي جالي
اهني جرغرض ييرتمام تالي اهنا واسط شهادة
اختيار كيدي، سون غرض؟كراسمانو زمين

In [8]:
for page in arabic_result:
    for line in page["rec_texts"]:
        print(line)

٧٨٦
مؤمنين ني جاعة اله سبحانه في خلقة
ما غوروفكركري ة هيشر ا اية في تلاوة نا
مَمَالَ الََلرحيَمِإِنَ
كرناركرين
في حَلَقِاَلسَمَوَتِ وَألْأَرضِ وَآختِلَفِ اَلّْلِ
لنَارَِ لُى الأَالَِ يَذكُنَ
الَ ِمَا وَعُدََى جُم وََكَرُونَ
في حَلقِلسَمَتِ َألأَرضِ رَنَاَاَقَ َذَا
طلَطَُا ُْحَتَك فَِنَاعَابَالَاِ
مثل ااية پزهي  اج تاسوع نادن ما
عاشوراء نا دن واسط تياري كرناراين سكلاي
كرجردن ما حسين يراخلقة باطل نزتي جالي
اهني جرغرض ييرتمام تالي اهنا واسط شهادة
اختيار كيدي، سون غرض؟كراسمانو زمين

In [9]:
from pathlib import Path

font_path = Path("build/Kanz-al-Marjaan-Regular.ttf")

print("Current directory:", Path.cwd())
print("Expected font path:", font_path.resolve())
print("Exists:", font_path.exists())

Current directory: c:\Users\ammar\OneDrive\Desktop\largelisaanmodel
Expected font path: C:\Users\ammar\OneDrive\Desktop\largelisaanmodel\build\Kanz-al-Marjaan-Regular.ttf
Exists: False

In [10]:
from pathlib import Path

for font_file in Path(".").rglob("*.ttf"):
    print(font_file.resolve())

C:\Users\ammar\OneDrive\Desktop\largelisaanmodel\Kanz-al-Marjaan-Regular.ttf
C:\Users\ammar\OneDrive\Desktop\largelisaanmodel\venv\Lib\site-packages\playwright\driver\package\lib\vite\dashboard\assets\codicon-DCmgc-ay.ttf
C:\Users\ammar\OneDrive\Desktop\largelisaanmodel\venv\Lib\site-packages\playwright\driver\package\lib\vite\recorder\assets\codicon-DCmgc-ay.ttf
C:\Users\ammar\OneDrive\Desktop\largelisaanmodel\venv\Lib\site-packages\playwright\driver\package\lib\vite\traceViewer\codicon.DCmgc-ay.ttf

In [13]:
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
import arabic_reshaper
from bidi.algorithm import get_display

FONT_PATH = Path(
    r"C:\Users\ammar\OneDrive\Desktop\largelisaanmodel\Kanz-al-Marjaan\build\Kanz-al-Marjaan-Regular.ttf"
)

OUTPUT_DIR = Path("synthetic_dataset/images")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

sentences = [
    "الله تعالى ني نعمت",
    "اپنے مولا ني ذكر",
    "پہلے مؤمنين نے عرض كيدو",
    "لئے مؤمنين ني جماعت",
    "بسم الله الرحمن الرحيم",
]

font = ImageFont.truetype(str(FONT_PATH), size=58)


labels = []

for index, text in enumerate(sentences, start=1):
    reshaped = arabic_reshaper.reshape(text)
    display_text = get_display(reshaped)

    canvas = Image.new("L", (1600, 150), 255)
    draw = ImageDraw.Draw(canvas)

    bbox = draw.textbbox((0, 0), display_text, font=font)
    text_width = bbox[2] - bbox[0]

    x = 1550 - text_width
    y = 35

    draw.text((x, y), display_text, font=font, fill=0)

    image_path = OUTPUT_DIR / f"line_{index:05d}.png"
    canvas.save(image_path)

    labels.append(f"{image_path.as_posix()}\t{text}")

Path("synthetic_dataset/train.txt").write_text(
    "\n".join(labels),
    encoding="utf-8",
)

OSError: cannot open resource

In [ ]:
from pathlib import Path
from fontTools.ttLib import TTFont
import json

FONT_PATH = Path(
    r"C:\Users\ammar\OneDrive\Desktop\largelisaanmodel\Kanz-al-Marjaan\build\Kanz-al-Marjaan-Regular.ttf"
)

font = TTFont(FONT_PATH)

# Glyph name -> Unicode character
glyph_to_unicode = {}
for codepoint, glyph in font.getBestCmap().items():
    glyph_to_unicode[glyph] = chr(codepoint)

gsub = font["GSUB"].table

mappings = {}

for lookup in gsub.LookupList.Lookup:

    # Only Ligature substitutions
    if lookup.LookupType != 4:
        continue

    for subtable in lookup.SubTable:

        for first, ligatures in subtable.ligatures.items():

            for lig in ligatures:

                # Build source sequence
                source = glyph_to_unicode.get(first, first)

                for g in lig.Component:
                    source += glyph_to_unicode.get(g, g)

                # Build target
                target = glyph_to_unicode.get(
                    lig.LigGlyph,
                    lig.LigGlyph
                )

                mappings[source] = target

# Save JSON
with open("kanz_mappings.json", "w", encoding="utf-8") as f:
    json.dump(
        mappings,
        f,
        ensure_ascii=False,
        indent=4
    )

print(f"Extracted {len(mappings)} mappings.")
print("Saved to kanz_mappings.json")

Extracted 1149 mappings.
Saved to kanz_mappings.json

## Dataset for QWEN Visual Learning model

In [69]:
from pathlib import Path
from collections import Counter
import unicodedata
import json
import os

import pandas as pd
from PIL import Image

In [70]:
PROJECT_ROOT = Path(r"C:\Users\ammar\OneDrive\Desktop\largelisaanmodel")

TRAIN_FILE = PROJECT_ROOT / "dataset/train_updated.txt"
VAL_FILE   = PROJECT_ROOT / "dataset/val_updated.txt"
TEST_FILE  = PROJECT_ROOT / "dataset/test_updated.txt"

OUTPUT_DIR = PROJECT_ROOT / "dataset_qwen"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("Project:", PROJECT_ROOT)
print("Output :", OUTPUT_DIR)

Project: C:\Users\ammar\OneDrive\Desktop\largelisaanmodel
Output : C:\Users\ammar\OneDrive\Desktop\largelisaanmodel\dataset_qwen

In [71]:
def load_labels(file_path, split_name):
    records = []

    with open(file_path, "r", encoding="utf-8-sig") as f:
        for line_number, line in enumerate(f, start=1):

            line = line.rstrip("\r\n")

            if not line.strip():
                continue

            parts = line.split("\t", 1)

            if len(parts) != 2:
                print(
                    f"WARNING: malformed line "
                    f"{line_number} in {file_path.name}"
                )
                continue

            image_path, text = parts

            records.append({
                "split": split_name,
                "line_number": line_number,
                "image": image_path.strip(),
                "text_original": text
            })

    return pd.DataFrame(records)


train_df = load_labels(TRAIN_FILE, "train")
val_df   = load_labels(VAL_FILE, "val")
test_df  = load_labels(TEST_FILE, "test")

print("Train:", len(train_df))
print("Val  :", len(val_df))
print("Test :", len(test_df))
print("Total:", len(train_df) + len(val_df) + len(test_df))

display(train_df.head())

Train: 3955
Val  : 465
Test : 234
Total: 4654

,split,line_number,image,text_original
0,train,1,dataset/images/train_000001_v01.png,اْپنا دل ني انے جه قران اْپنا دل پر اترا يه سگ...
1,train,2,dataset/images/train_000002_v01.png,آرزو رهي جائي ،
2,train,3,dataset/images/train_000003_v01.png,ﻛﻪ ﺟﻬ ني معنى پاك ني ؛،
3,train,4,dataset/images/train_000004_v01.png,والحمد الله رب العالمين،
4,train,5,dataset/images/train_000005_v01.png,ﺑﻬلا ايم كيم ﻧﻬ هوئي!

In [72]:
def resolve_image_path(relative_path):
    relative_path = relative_path.replace("\\", "/")
    return PROJECT_ROOT / Path(relative_path)


for df in [train_df, val_df, test_df]:
    df["full_image_path"] = df["image"].apply(resolve_image_path)

display(train_df[["image", "full_image_path"]].head())

,image,full_image_path
0,dataset/images/train_000001_v01.png,C:\Users\ammar\OneDrive\Desktop\largelisaanmod...
1,dataset/images/train_000002_v01.png,C:\Users\ammar\OneDrive\Desktop\largelisaanmod...
2,dataset/images/train_000003_v01.png,C:\Users\ammar\OneDrive\Desktop\largelisaanmod...
3,dataset/images/train_000004_v01.png,C:\Users\ammar\OneDrive\Desktop\largelisaanmod...
4,dataset/images/train_000005_v01.png,C:\Users\ammar\OneDrive\Desktop\largelisaanmod...

In [76]:
import pandas as pd

ENGLISH_DIGITS = "0123456789"
ARABIC_DIGITS  = "٠١٢٣٤٥٦٧٨٩"
PERSIAN_DIGITS = "۰۱۲۳۴۵۶۷۸۹"

ALL_DIGITS = ENGLISH_DIGITS + ARABIC_DIGITS + PERSIAN_DIGITS


def find_numerals_in_txt(txt_path, split_name):
    results = []

    with open(txt_path, "r", encoding="utf-8") as f:

        for line_number, line in enumerate(f, start=1):

            line = line.rstrip("\n\r")

            if not line.strip():
                continue

            # Split ONLY on first tab
            parts = line.split("\t", 1)

            if len(parts) != 2:
                continue

            image_path, label = parts

            digits = "".join(
                c for c in label
                if c in ALL_DIGITS
            )

            if not digits:
                continue

            systems = []

            if any(c in ENGLISH_DIGITS for c in label):
                systems.append("English")

            if any(c in ARABIC_DIGITS for c in label):
                systems.append("Arabic")

            if any(c in PERSIAN_DIGITS for c in label):
                systems.append("Persian")

            results.append({
                "split": split_name,
                "line": line_number,
                "image": image_path,
                "label": label,
                "digits": digits,
                "numeral_system": ", ".join(systems),
            })

    return results

In [77]:
train_numerals = find_numerals_in_txt(
    TRAIN_FILE,
    "train"
)

val_numerals = find_numerals_in_txt(
    VAL_FILE,
    "val"
)

test_numerals = find_numerals_in_txt(
    TEST_FILE,
    "test"
)

numeral_df = pd.DataFrame(
    train_numerals
    + val_numerals
    + test_numerals
)

print("Total numeral samples:", len(numeral_df))

display(numeral_df)

Total numeral samples: 103

,split,line,image,label,digits,numeral_system
0,train,32,dataset/images/train_000032_v01.png,يه مولانا عبد علي سيف الدين يه عجب شان سي اْپن...,4,English
1,train,50,dataset/images/train_000050_v01.png,6 ازالة المدرسة السلحدار الابتدائية,6,English
2,train,54,dataset/images/train_000054_v01.png,انے 8 ورس لگن اْپ رسول االله نا ساتهے انے مولا...,8,English
3,train,73,dataset/images/train_000073_v01.png,تو 69 مغفرة تميں سنو كئي مغفرةﻛﻪ ﺟﻬ ﻧﺎ سبب خدا...,69,English
4,train,98,dataset/images/train_000098_v01.png,ته بعد وه دهاكنو هتايو تو 10 ميٹر نو كهدّو هتو...,10560,English
...,...,...,...,...,...,...
98,test,127,dataset/images/test_000127_v01.png,ترميم درميان مسجد ما سي تقريبا 4000 Trucks جتن...,4000,English
99,test,139,dataset/images/test_000139_v01.png,ربيع الاول سنة 1400هـ ما الباب الرئيسي نا نزدي...,14006,English
100,test,174,dataset/images/test_000174_v01.png,المجلس السادس 1418هـ,1418,English
101,test,184,dataset/images/test_000184_v01.png,تو اسﺑﺎغ الوضوء ني سوں معنى ﻛﻪ اْورن هووي جوئي...,1941,English
102,test,234,dataset/images/test_000234_v01.png,اﻟﻤﺠلس الﺛﺎني – 1437,1437,English

In [78]:
ENGLISH_TO_ARABIC_DIGITS = str.maketrans(
    "0123456789",
    "٠١٢٣٤٥٦٧٨٩"
)

In [79]:
text = "مظظوٹي"

for ch in text:
    print(
        repr(ch),
        f"U+{ord(ch):04X}",
        unicodedata.name(ch, "UNKNOWN")
    )

'م' U+0645 ARABIC LETTER MEEM
'ظ' U+0638 ARABIC LETTER ZAH
'ظ' U+0638 ARABIC LETTER ZAH
'و' U+0648 ARABIC LETTER WAW
'ٹ' U+0679 ARABIC LETTER TTEH
'ي' U+064A ARABIC LETTER YEH

In [80]:
from fontTools.ttLib import TTFont

FONT_PATH = r"C:\Users\ammar\OneDrive\Desktop\largelisaanmodel\Kanz-al-Marjaan-Regular.ttf"

font = TTFont(FONT_PATH)

cmap = {}

for table in font["cmap"].tables:
    cmap.update(table.cmap)

for cp in [ord("ظ")]:
    print(
        hex(cp),
        chr(cp),
        "->",
        cmap.get(cp)
    )

0x638 ظ -> uni0638

In [81]:
gsub = font["GSUB"].table

for lookup in gsub.LookupList.Lookup:
    if lookup.LookupType != 4:
        continue

    for subtable in lookup.SubTable:
        if not hasattr(subtable, "ligatures"):
            continue

        for first_glyph, ligatures in subtable.ligatures.items():

            for lig in ligatures:

                sequence = [first_glyph] + lig.Component

                print(
                    sequence,
                    "->",
                    lig.LigGlyph
                )

['uni064B', 'uni0651'] -> uni0651064B
['uni064C', 'uni0651'] -> uni0651064C
['uni064D', 'uni0651'] -> uni0651064D
['uni064E', 'uni0651'] -> uni0651064E
['uni064F', 'uni0651'] -> uni0651064F
['uni0650', 'uni0651'] -> uni06510650
['uni0651', 'uni064B'] -> uni0651064B
['uni0651', 'uni064C'] -> uni0651064C
['uni0651', 'uni064D'] -> uni0651064D
['uni0651', 'uni064E'] -> uni0651064E
['uni0651', 'uni064F'] -> uni0651064F
['uni0651', 'uni0650'] -> uni06510650
['uni0651', 'uni0670'] -> uni06510670
['uni0654', 'uni064E'] -> uni0654064E
['uni0654', 'uni064F'] -> uni0654064F
['uni0654', 'uni0652'] -> uni06540652
['uni0655', 'uni0650'] -> uni06550650
['uni0670', 'uni0651'] -> uni06510670
['uniFB7C', 'uniFEC8', 'uniFEC8'] -> glyph1955
['uniFE9B', 'uniFE9A'] -> uni067E
['uniFE9B', 'uniFE9C'] -> uniFB58
['uniFE9C', 'uniFE9A'] -> uniFB57
['uniFE9C', 'uniFE9C'] -> uniFB59
['uniFE9F', 'uniFEC8', 'uniFEC8'] -> glyph1956
['uniFEA3', 'uniFEA4', 'uniFEC8', 'uniFEC8'] -> glyph1955
['uniFEA3', 'uniFEC8', 'uniFEC8'] -> glyph1957
['uniFEA3', 'uniFEA2'] -> uni0686
['uniFEA3', 'uniFEA4'] -> uniFB7C
['uniFEA4', 'uniFEA2'] -> uniFB7B
['uniFEA4', 'uniFEA4'] -> uniFB7D
['uniFEA7', 'uniFEC8', 'uniFEC8'] -> glyph1958
['uniFEB3', 'uniFEB2'] -> uni06D2
['uniFEB4', 'uniFEB2'] -> uniFBAF
['uniFEBB', 'uniFEBA'] -> base.behisol
['uniFEBC', 'uniFEBA'] -> base.behfinal
['uniFEBF', 'uniFEBE'] -> uni0679
['uniFEBF', 'uniFEC0'] -> uniFB68
['uniFEC0', 'uniFEBE'] -> uniFB67
['uniFEC0', 'uniFEC0'] -> uni0679.tall.medi
['uniFEC3', 'uniFEC8', 'uniFEC8'] -> glyph2169
['uniFEC3', 'uniFEC2'] -> uni06BA
['uniFEC4', 'uniFEC2'] -> uniFB9F
['uniFEC7', 'uniFEC8', 'uniFEC6'] -> glyph2170
['uniFEC7', 'uniFEC8', 'uniFEC8'] -> glyph2170
['uniFEC8', 'uniFEC8', 'uniFEC6'] -> glyph1565
['uniFEC8', 'uniFEC8', 'uniFEC8'] -> glyph1565
['uniFEC8', 'uniFEC6'] -> liga.behhehmedi
['uniFEC8', 'uniFEC8'] -> liga.behhehmedi
['uniFECB', 'uniFEC8', 'uniFEC8'] -> glyph2162
['uniFECF', 'uniFEC8', 'uniFEC8'] -> glyph2163
['uniFED3', 'uniFEC8', 'uniFEC8'] -> glyph2165
['uniFED7', 'uniFEC8', 'uniFEC8'] -> glyph2166
['uniFEDB', 'uniFEDA'] -> uni06AF
['uniFEDB', 'uniFEDC'] -> uniFB94
['uniFEDC', 'uniFEDA'] -> uniFB93
['uniFEDC', 'uniFEDC'] -> uniFB95
['uniFEDF', 'uniFE82'] -> uniFEF5
['uniFEDF', 'uniFE84'] -> uniFEF7
['uniFEDF', 'uniFE88'] -> uniFEF9
['uniFEDF', 'uniFE8E'] -> uniFEFB
['uniFEDF', 'uni0627.short.fina'] -> lamalefarab.alt1.isol
['uniFEE0', 'uniFE82'] -> uniFEF6
['uniFEE0', 'uniFE84'] -> uniFEF8
['uniFEE0', 'uniFE88'] -> uniFEFA
['uniFEE0', 'uniFE8E'] -> uniFEFC
['uniFEE0', 'uni0627.short.fina'] -> lamalefarab.alt1.fina
['uniFEE3', 'uniFEA4', 'uniFEE4', 'uniFEAA'] -> MHMD.liga
['uniFBE8', 'uniFE8E'] -> uni06490627.isol
['uniFBFE', 'uniFE8E'] -> uni064A0627.isol
['uniFE91', 'uniFE8E'] -> uni06280627.isol
['uniFE97', 'uniFE8E'] -> uni062A0627.isol
['uniFE9B', 'uniFE8E'] -> uni062B0627.isol
['uniFEE7', 'uniFE8E'] -> uni06460627.isol
['uniFB58', 'uniFEEC', 'uni0640'] -> uni067E06BE0640.liga.init.medi
['uniFB58', 'uniFEEC', 'uniFBAF'] -> uni067E06BE06D2.liga.init.medi.fina
['uniFB58', 'uniFEEC'] -> uni067E06BE.liga.init.medi
['uniFB58', 'liga.behhehmedi'] -> uni067D0647.init
['uniFB59', 'uniFEEC', 'uniFBAF'] -> uni067E06BE06D2.liga.medi.medi.fina
['uniFB59', 'liga.behhehmedi', 'uniFEF0'] -> uni067E06470649.liga.medi.medi.fina
['uniFB59', 'liga.behhehmedi', 'uniFEF2'] -> uni067E0647064A.liga.medi.medi.fina
['uniFB59', 'uniFEEC'] -> uni067E06BE.liga.medi.medi
['uniFB59', 'liga.behhehmedi'] -> uni067D0647.medi
['uniFB68', 'uniFEEC', 'uni0640'] -> uni067906BE0640.liga.init.medi
['uniFB68', 'uniFEEC', 'uniFBAF'] -> uni067906BE06D2.liga.init.medi.fina
['uniFB68', 'liga.behhehmedi', 'uniFB7B'] -> uni067906470686.liga.init.medi.fina
['uniFB68', 'liga.behhehmedi', 'uniFB7D'] -> uni067906470686.liga.init.medi.medi
['uniFB68', 'liga.behhehmedi', 'uniFE9E'] -> uni06790647062C.liga.init.medi.fina
['uniFB68', 'liga.behhehmedi', 'uniFEA0'] -> uni06790647062C.liga.init.medi.medi
['uniFB68', 'liga.behhehmedi', 'uniFEA2'] -> uni06790647062D.liga.init.medi.fina
['uniFB68', 'liga.behhehmedi', 'uniFEA4'] -> uni06790647062D.liga.init.medi.medi
['uniFB68', 'liga.behhehmedi', 'uniFEA6'] -> uni06790647062E.liga.init.medi.fina
['uniFB68', 'liga.behhehmedi', 'uniFEA8'] -> uni06790647062E.liga.init.medi.medi
['uniFB68', 'liga.behhehmedi', 'uniFEE2'] -> uni067906470645.liga.init.medi.fina
['uniFB68', 'uniFEEC'] -> uni067906BE.liga.init.medi
['uniFB68', 'liga.behhehmedi'] -> uni06790647.init
['uniFB69', 'uniFEEC', 'uniFBAF'] -> uni067906BE06D2.liga.medi.medi.fina
['uniFB69', 'liga.behhehmedi', 'uniFB7B'] -> uni067906470686.liga.medi.medi.fina
['uniFB69', 'liga.behhehmedi', 'uniFE9E'] -> uni06790647062C.liga.medi.medi.fina
['uniFB69', 'liga.behhehmedi', 'uniFEA2'] -> uni06790647062D.liga.medi.medi.fina
['uniFB69', 'liga.behhehmedi', 'uniFEA6'] -> uni06790647062E.liga.medi.medi.fina
['uniFB69', 'liga.behhehmedi', 'uniFEE2'] -> uni067906470645.liga.medi.medi.fina
['uniFB69', 'liga.behhehmedi', 'uniFEF0'] -> uni067906470649.liga.medi.medi.fina
['uniFB69', 'liga.behhehmedi', 'uniFEF2'] -> uni06790647064A.liga.medi.medi.fina
['uniFB69', 'uniFEEC'] -> uni067906BE.liga.medi.medi
['uniFB69', 'liga.behhehmedi'] -> uni06790647.medi
['uniFBFE', 'uniFEEC', 'uni0640'] -> uni064A06BE0640.liga.init.medi
['uniFBFE', 'uniFEEC', 'uniFBAF'] -> uni064A06BE06D2.liga.init.medi.fina
['uniFBFE', 'liga.behhehmedi', 'uniFB7B'] -> uni064A06470686.liga.init.medi.fina
['uniFBFE', 'liga.behhehmedi', 'uniFB7D'] -> uni064A06470686.liga.init.medi.medi
['uniFBFE', 'liga.behhehmedi', 'uniFE9E'] -> uni064A0647062C.liga.init.medi.fina
['uniFBFE', 'liga.behhehmedi', 'uniFEA0'] -> uni064A0647062C.liga.init.medi.medi
['uniFBFE', 'liga.behhehmedi', 'uniFEA2'] -> uni064A0647062D.liga.init.medi.fina
['uniFBFE', 'liga.behhehmedi', 'uniFEA4'] -> uni064A0647062D.liga.init.medi.medi
['uniFBFE', 'liga.behhehmedi', 'uniFEA6'] -> uni064A0647062E.liga.init.medi.fina
['uniFBFE', 'liga.behhehmedi', 'uniFEA8'] -> uni064A0647062E.liga.init.medi.medi
['uniFBFE', 'liga.behhehmedi', 'uniFEE2'] -> uni064A06470645.liga.init.medi.fina
['uniFBFE', 'uniFEEC'] -> uni064A06BE.liga.init.medi
['uniFBFE', 'liga.behhehmedi'] -> uniFCDE
['uniFBFF', 'uniFEEC', 'uniFBAF'] -> uni064A06BE06D2.liga.medi.medi.fina
['uniFBFF', 'liga.behhehmedi', 'uniFB7B'] -> uni064A06470686.liga.medi.medi.fina
['uniFBFF', 'liga.behhehmedi', 'uniFE9E'] -> uni064A0647062C.liga.medi.medi.fina
['uniFBFF', 'liga.behhehmedi', 'uniFEA2'] -> uni064A0647062D.liga.medi.medi.fina
['uniFBFF', 'liga.behhehmedi', 'uniFEA6'] -> uni064A0647062E.liga.medi.medi.fina
['uniFBFF', 'liga.behhehmedi', 'uniFEE2'] -> uni064A06470645.liga.medi.medi.fina
['uniFBFF', 'liga.behhehmedi', 'uniFEF0'] -> uni064A06470649.liga.medi.medi.fina
['uniFBFF', 'liga.behhehmedi', 'uniFEF2'] -> uni064A0647064A.liga.medi.medi.fina
['uniFBFF', 'uniFEEC'] -> uni064A06BE.liga.medi.medi
['uniFBFF', 'liga.behhehmedi'] -> uniFCF1
['uniFE8B', 'uniFEEC', 'uni0640'] -> uni062606BE0640.liga.init.medi
['uniFE8B', 'uniFEEC', 'uniFBAF'] -> uni062606BE06D2.liga.init.medi.fina
['uniFE8B', 'liga.behhehmedi', 'uniFB7B'] -> uni062606470686.liga.init.medi.fina
['uniFE8B', 'liga.behhehmedi', 'uniFB7D'] -> uni062606470686.liga.init.medi.medi
['uniFE8B', 'liga.behhehmedi', 'uniFE9E'] -> uni06260647062C.liga.init.medi.fina
['uniFE8B', 'liga.behhehmedi', 'uniFEA0'] -> uni06260647062C.liga.init.medi.medi
['uniFE8B', 'liga.behhehmedi', 'uniFEA2'] -> uni06260647062D.liga.init.medi.fina
['uniFE8B', 'liga.behhehmedi', 'uniFEA4'] -> uni06260647062D.liga.init.medi.medi
['uniFE8B', 'liga.behhehmedi', 'uniFEA6'] -> uni06260647062E.liga.init.medi.fina
['uniFE8B', 'liga.behhehmedi', 'uniFEA8'] -> uni06260647062E.liga.init.medi.medi
['uniFE8B', 'liga.behhehmedi', 'uniFEE2'] -> uni062606470645.liga.init.medi.fina
['uniFE8B', 'uniFEEC'] -> uni062606BE.liga.init.medi
['uniFE8B', 'liga.behhehmedi'] -> uniFC9B
['uniFE8C', 'uniFEEC', 'uniFBAF'] -> uni062606BE06D2.liga.medi.medi.fina
['uniFE8C', 'liga.behhehmedi', 'uniFB7B'] -> uni062606470686.liga.medi.medi.fina
['uniFE8C', 'liga.behhehmedi', 'uniFE9E'] -> uni06260647062C.liga.medi.medi.fina
['uniFE8C', 'liga.behhehmedi', 'uniFEA2'] -> uni06260647062D.liga.medi.medi.fina
['uniFE8C', 'liga.behhehmedi', 'uniFEE2'] -> uni062606470645.liga.medi.medi.fina
['uniFE8C', 'liga.behhehmedi', 'uniFEF0'] -> uni062606470649.liga.medi.medi.fina
['uniFE8C', 'liga.behhehmedi', 'uniFEF2'] -> uni06260647064A.liga.medi.medi.fina
['uniFE8C', 'uniFEEC'] -> uni062606BE.liga.medi.medi
['uniFE8C', 'liga.behhehmedi'] -> uniFCE0
['uniFE91', 'uniFEEC', 'uni0640'] -> uni062806BE0640.liga.init.medi
['uniFE91', 'uniFEEC', 'uniFBAF'] -> uni062806BE06D2.liga.init.medi.fina
['uniFE91', 'liga.behhehmedi', 'uniFB7B'] -> uni062806470686.liga.init.medi.fina
['uniFE91', 'liga.behhehmedi', 'uniFB7D'] -> uni062806470686.liga.init.medi.medi
['uniFE91', 'liga.behhehmedi', 'uniFE9E'] -> uni06280647062C.liga.init.medi.fina
['uniFE91', 'liga.behhehmedi', 'uniFEA0'] -> uni06280647062C.liga.init.medi.medi
['uniFE91', 'liga.behhehmedi', 'uniFEA2'] -> uni06280647062D.liga.init.medi.fina
['uniFE91', 'liga.behhehmedi', 'uniFEA4'] -> uni06280647062D.liga.init.medi.medi
['uniFE91', 'liga.behhehmedi', 'uniFEA6'] -> uni06280647062E.liga.init.medi.fina
['uniFE91', 'liga.behhehmedi', 'uniFEA8'] -> uni06280647062E.liga.init.medi.medi
['uniFE91', 'liga.behhehmedi', 'uniFEE2'] -> uni062806470645.liga.init.medi.fina
['uniFE91', 'uniFEEC'] -> uni062806BE.liga.init.medi
['uniFE91', 'liga.behhehmedi'] -> uniFCA0
['uniFE92', 'uniFEEC', 'uniFBAF'] -> uni062806BE06D2.liga.medi.medi.fina
['uniFE92', 'liga.behhehmedi', 'uniFB7B'] -> uni062806470686.liga.medi.medi.fina
['uniFE92', 'liga.behhehmedi', 'uniFE9E'] -> uni06280647062C.liga.medi.medi.fina
['uniFE92', 'liga.behhehmedi', 'uniFEA2'] -> uni06280647062D.liga.medi.medi.fina
['uniFE92', 'liga.behhehmedi', 'uniFEA6'] -> uni06280647062E.liga.medi.medi.fina
['uniFE92', 'liga.behhehmedi', 'uniFEE2'] -> uni062806470645.liga.medi.medi.fina
['uniFE92', 'liga.behhehmedi', 'uniFEF0'] -> uni062806470649.liga.medi.medi.fina
['uniFE92', 'liga.behhehmedi', 'uniFEF2'] -> uni06280647064A.liga.medi.medi.fina
['uniFE92', 'uniFEEC'] -> uni062806BE.liga.medi.medi
['uniFE92', 'liga.behhehmedi'] -> uniFCE2
['uniFE97', 'uniFEEC', 'uni0640'] -> uni062A06BE0640.liga.init.medi
['uniFE97', 'uniFEEC', 'uniFBAF'] -> uni062A06BE06D2.liga.init.medi.fina
['uniFE97', 'liga.behhehmedi', 'uniFB7B'] -> uni062A06470686.liga.init.medi.fina
['uniFE97', 'liga.behhehmedi', 'uniFB7D'] -> uni062A06470686.liga.init.medi.medi
['uniFE97', 'liga.behhehmedi', 'uniFE9E'] -> uni062A0647062C.liga.init.medi.fina
['uniFE97', 'liga.behhehmedi', 'uniFEA0'] -> uni062A0647062C.liga.init.medi.medi
['uniFE97', 'liga.behhehmedi', 'uniFEA2'] -> uni062A0647062D.liga.init.medi.fina
['uniFE97', 'liga.behhehmedi', 'uniFEA4'] -> uni062A0647062D.liga.init.medi.medi
['uniFE97', 'liga.behhehmedi', 'uniFEA6'] -> uni062A0647062E.liga.init.medi.fina
['uniFE97', 'liga.behhehmedi', 'uniFEA8'] -> uni062A0647062E.liga.init.medi.medi
['uniFE97', 'liga.behhehmedi', 'uniFEE2'] -> uni062A06470645.liga.init.medi.fina
['uniFE97', 'uniFEEC'] -> uni062A06BE.liga.init.medi
['uniFE97', 'liga.behhehmedi'] -> uniFCA5
['uniFE98', 'uniFEEC', 'uniFBAF'] -> uni062A06BE06D2.liga.medi.medi.fina
['uniFE98', 'liga.behhehmedi', 'uniFB7B'] -> uni062A06470686.liga.medi.medi.fina
['uniFE98', 'liga.behhehmedi', 'uniFE9E'] -> uni062A0647062C.liga.medi.medi.fina
['uniFE98', 'liga.behhehmedi', 'uniFEA2'] -> uni062A0647062D.liga.medi.medi.fina
['uniFE98', 'liga.behhehmedi', 'uniFEA6'] -> uni062A0647062E.liga.medi.medi.fina
['uniFE98', 'liga.behhehmedi', 'uniFEE2'] -> uni062A06470645.liga.medi.medi.fina
['uniFE98', 'liga.behhehmedi', 'uniFEF0'] -> uni062A06470649.liga.medi.medi.fina
['uniFE98', 'liga.behhehmedi', 'uniFEF2'] -> uni062A0647064A.liga.medi.medi.fina
['uniFE98', 'uniFEEC'] -> uni062A06BE.liga.medi.medi
['uniFE98', 'liga.behhehmedi'] -> uniFCE4
['uniFE9B', 'uniFEEC', 'uni0640'] -> uni062B06BE0640.liga.init.medi
['uniFE9B', 'uniFEEC', 'uniFBAF'] -> uni062B06BE06D2.liga.init.medi.fina
['uniFE9B', 'liga.behhehmedi', 'uniFB7B'] -> uni062B06470686.liga.init.medi.fina
['uniFE9B', 'liga.behhehmedi', 'uniFB7D'] -> uni062B06470686.liga.init.medi.medi
['uniFE9B', 'liga.behhehmedi', 'uniFE9E'] -> uni062B0647062C.liga.init.medi.fina
['uniFE9B', 'liga.behhehmedi', 'uniFEA0'] -> uni062B0647062C.liga.init.medi.medi
['uniFE9B', 'liga.behhehmedi', 'uniFEA2'] -> uni062B0647062D.liga.init.medi.fina
['uniFE9B', 'liga.behhehmedi', 'uniFEA4'] -> uni062B0647062D.liga.init.medi.medi
['uniFE9B', 'liga.behhehmedi', 'uniFEA6'] -> uni062B0647062E.liga.init.medi.fina
['uniFE9B', 'liga.behhehmedi', 'uniFEA8'] -> uni062B0647062E.liga.init.medi.medi
['uniFE9B', 'liga.behhehmedi', 'uniFEE2'] -> uni062B06470645.liga.init.medi.fina
['uniFE9B', 'uniFEEC'] -> uni062B06BE.liga.init.medi
['uniFE9C', 'uniFEEC', 'uniFBAF'] -> uni062B06BE06D2.liga.medi.medi.fina
['uniFE9C', 'liga.behhehmedi', 'uniFB7B'] -> uni062B06470686.liga.medi.medi.fina
['uniFE9C', 'liga.behhehmedi', 'uniFE9E'] -> uni062B0647062C.liga.medi.medi.fina
['uniFE9C', 'liga.behhehmedi', 'uniFEA2'] -> uni062B0647062D.liga.medi.medi.fina
['uniFE9C', 'liga.behhehmedi', 'uniFEA6'] -> uni062B0647062E.liga.medi.medi.fina
['uniFE9C', 'liga.behhehmedi', 'uniFEE2'] -> uni062B06470645.liga.medi.medi.fina
['uniFE9C', 'liga.behhehmedi', 'uniFEF0'] -> uni062B06470649.liga.medi.medi.fina
['uniFE9C', 'liga.behhehmedi', 'uniFEF2'] -> uni062B0647064A.liga.medi.medi.fina
['uniFE9C', 'uniFEEC'] -> uni062B06BE.liga.medi.medi
['uniFE9C', 'liga.behhehmedi'] -> uniFCE6
['uniFEE3', 'uniFEEC'] -> uni064506BE.liga.init.medi
['uniFEE3', 'liga.behhehmedi'] -> uni06450647.liga.init.medi
['uniFEE7', 'uniFEEC', 'uni0640'] -> uni064606BE0640.liga.init.medi
['uniFEE7', 'uniFEEC', 'uniFBAF'] -> uni064606BE06D2.liga.init.medi.fina
['uniFEE7', 'liga.behhehmedi', 'uniFB7B'] -> uni064606470686.liga.init.medi.fina
['uniFEE7', 'liga.behhehmedi', 'uniFB7D'] -> uni064606470686.liga.init.medi.medi
['uniFEE7', 'liga.behhehmedi', 'uniFE9E'] -> uni06460647062C.liga.init.medi.fina
['uniFEE7', 'liga.behhehmedi', 'uniFEA0'] -> uni06460647062C.liga.init.medi.medi
['uniFEE7', 'liga.behhehmedi', 'uniFEA2'] -> uni06460647062D.liga.init.medi.fina
['uniFEE7', 'liga.behhehmedi', 'uniFEA4'] -> uni06460647062D.liga.init.medi.medi
['uniFEE7', 'liga.behhehmedi', 'uniFEA6'] -> uni06460647062E.liga.init.medi.fina
['uniFEE7', 'liga.behhehmedi', 'uniFEA8'] -> uni06460647062E.liga.init.medi.medi
['uniFEE7', 'liga.behhehmedi', 'uniFEE2'] -> uni064606470645.liga.init.medi.fina
['uniFEE7', 'uniFEEC'] -> uni064606BE.liga.init.medi
['uniFEE7', 'liga.behhehmedi'] -> uniFCD6
['uniFEE8', 'uniFEEC', 'uniFBAF'] -> uni064606BE06D2.liga.medi.medi.fina
['uniFEE8', 'liga.behhehmedi', 'uniFB7B'] -> uni064606470686.liga.medi.medi.fina
['uniFEE8', 'liga.behhehmedi', 'uniFE9E'] -> uni06460647062C.liga.medi.medi.fina
['uniFEE8', 'liga.behhehmedi', 'uniFEA2'] -> uni06460647062D.liga.medi.medi.fina
['uniFEE8', 'liga.behhehmedi', 'uniFEA6'] -> uni06460647062E.liga.medi.medi.fina
['uniFEE8', 'liga.behhehmedi', 'uniFEE2'] -> uni064606470645.liga.medi.medi.fina
['uniFEE8', 'liga.behhehmedi', 'uniFEF0'] -> uni064606470649.liga.medi.medi.fina
['uniFEE8', 'liga.behhehmedi', 'uniFEF2'] -> uni06460647064A.liga.medi.medi.fina
['uniFEE8', 'uniFEEC'] -> uni064606BE.liga.medi.medi
['uniFEE8', 'liga.behhehmedi'] -> uniFCEF
['uniFEEC', 'uniFEF0'] -> uni06470649.liga.medi.fina
['uniFEEC', 'uniFEF2'] -> uni0647064A.liga.medi.fina
['uniFB58', 'uniFB59', 'uniFBAF'] -> uni067E067E06D2.liga.init.medi.fina
['uniFB58', 'uniFB69', 'uniFBAF'] -> uni067E067906D2.liga.init.medi.fina
['uniFB58', 'uniFBFF', 'uniFBAF'] -> uni067E064A06D2.liga.init.medi.fina
['uniFB58', 'uniFE8C', 'uniFBAF'] -> uni067E062606D2.liga.init.medi.fina
['uniFB58', 'uniFE92', 'uniFBAF'] -> uni067E062806D2.liga.init.medi.fina
['uniFB58', 'uniFE98', 'uniFBAF'] -> uni067E062A06D2.liga.init.medi.fina
['uniFB58', 'uniFE9C', 'uniFBAF'] -> uni067E062B06D2.liga.init.medi.fina
['uniFB58', 'uniFEE8', 'uniFBAF'] -> uni067E064606D2.liga.init.medi.fina
['uniFB58', 'uniFEEC', 'uniFBAF'] -> uni067E06BE06D2.liga.init.medi.fina
['uniFB58', 'uniFBAF'] -> uni067E06D2.isol
['uniFB58', 'uniFBB1'] -> uni067E06D3.isol
['uniFB59', 'uniFB59', 'uniFBAF'] -> uni067E067E06D2.liga.medi.medi.fina
['uniFB59', 'uniFB69', 'uniFBAF'] -> uni067E067906D2.liga.medi.medi.fina
['uniFB59', 'uniFBFF', 'uniFBAF'] -> uni067E064A06D2.liga.medi.medi.fina
['uniFB59', 'uniFE8C', 'uniFBAF'] -> uni067E062606D2.liga.medi.medi.fina
['uniFB59', 'uniFE92', 'uniFBAF'] -> uni067E062806D2.liga.medi.medi.fina
['uniFB59', 'uniFE98', 'uniFBAF'] -> uni067E062A06D2.liga.medi.medi.fina
['uniFB59', 'uniFE9C', 'uniFBAF'] -> uni067E062B06D2.liga.medi.medi.fina
['uniFB59', 'uniFEE8', 'uniFBAF'] -> uni067E064606D2.liga.medi.medi.fina
['uniFB68', 'uniFB59', 'uniFBAF'] -> uni0679067E06D2.liga.init.medi.fina
['uniFB68', 'uniFB69', 'uniFBAF'] -> uni0679067906D2.liga.init.medi.fina
['uniFB68', 'uniFBFF', 'uniFBAF'] -> uni0679064A06D2.liga.init.medi.fina
['uniFB68', 'uniFE8C', 'uniFBAF'] -> uni0679062606D2.liga.init.medi.fina
['uniFB68', 'uniFE92', 'uniFBAF'] -> uni0679062806D2.liga.init.medi.fina
['uniFB68', 'uniFE98', 'uniFBAF'] -> uni0679062A06D2.liga.init.medi.fina
['uniFB68', 'uniFE9C', 'uniFBAF'] -> uni0679062B06D2.liga.init.medi.fina
['uniFB68', 'uniFEE8', 'uniFBAF'] -> uni0679064606D2.liga.init.medi.fina
['uniFB68', 'uniFEEC', 'uniFBAF'] -> uni067906BE06D2.liga.init.medi.fina
['uniFB68', 'uniFBAF'] -> uni067906D2.isol
['uniFB68', 'uniFBB1'] -> uni067906D3.isol
['uniFB69', 'uniFB59', 'uniFBAF'] -> uni0679067E06D2.liga.medi.medi.fina
['uniFB69', 'uniFB69', 'uniFBAF'] -> uni0679067906D2.liga.medi.medi.fina
['uniFB69', 'uniFBFF', 'uniFBAF'] -> uni0679064A06D2.liga.medi.medi.fina
['uniFB69', 'uniFE8C', 'uniFBAF'] -> uni0679062606D2.liga.medi.medi.fina
['uniFB69', 'uniFE92', 'uniFBAF'] -> uni0679062806D2.liga.medi.medi.fina
['uniFB69', 'uniFE98', 'uniFBAF'] -> uni0679062A06D2.liga.medi.medi.fina
['uniFB69', 'uniFE9C', 'uniFBAF'] -> uni0679062B06D2.liga.medi.medi.fina
['uniFB69', 'uniFEE8', 'uniFBAF'] -> uni0679064606D2.liga.medi.medi.fina
['uniFB7C', 'uniFBAD', 'uniFBAF'] -> uni068606BE06D2.isol
['uniFB7C', 'uniFEE0', 'uniFBAF'] -> uni0686064406D2.isol
['uniFB7C', 'uniFEEC', 'uniFBAF'] -> uni068606BE06D2.isol
['uniFB7C', 'uniFBAF'] -> uni068606D2.isol
['uniFB7C', 'uniFBB1'] -> uni068606D3.isol
['uniFB7C', 'uniFEEC'] -> uni068606BE.liga.init.medi
['uniFB7D', 'uniFE98', 'uniFBAF'] -> uni0686062A06D2.fina
['uniFB7D', 'uniFEEC', 'uniFBAF'] -> uni068606BE06D2.fina
['uniFB7D', 'uniFBAF'] -> uni068606D2.fina
['uniFB90', 'uniFBAF'] -> uni06A906D2.isol
['uniFB90', 'uniFBB1'] -> uni06A906D3.isol
['uniFB94', 'uniFEE0', 'uniFBAF'] -> uni06AF064406D2.isol
['uniFB94', 'uniFBAF'] -> uni06AF06D2.isol
['uniFB94', 'uniFBB1'] -> uni06AF06D3.isol
['uniFBA8', 'uniFBFF', 'uniFBAF'] -> uni06C106CC06D2.isol
['uniFBA8', 'uniFE98', 'uniFBAF'] -> uni06C1062A06D2.isol
['uniFBA8', 'uniFEE8', 'uniFBAF'] -> uni06C1064606D2.isol
['uniFBA8', 'uniFBAF'] -> uni06C106D2.isol
['uniFBA8', 'uniFBB1'] -> uni06C106D3.isol
['uniFBA9', 'uniFE98', 'uniFBAF'] -> uni06C1062A06D2.fina
['uniFBA9', 'uniFEE0', 'uniFBAF'] -> uni06C1064406D2.fina
['uniFBAC', 'uniFE98', 'uniFBAF'] -> uni06BE062A06D2.isol
['uniFBAC', 'uniFEB4', 'uniFBAF'] -> uni0647063306D2.liga.init.medi.fina
['uniFBAC', 'uniFEB8', 'uniFBAF'] -> uni0647063406D2.liga.init.medi.fina
['uniFBAC', 'uniFEE8', 'uniFBAF'] -> uni06BE064606D2.isol
['uniFBAC', 'uniFBAF'] -> uni06BE06D2.isol
['uniFBAC', 'uniFBB1'] -> uni06BE06D3.isol
['uniFBE8', 'uniFBAF'] -> uni064906D2.isol
['uniFBFE', 'uniFB59', 'uniFBAF'] -> uni064A067E06D2.liga.init.medi.fina
['uniFBFE', 'uniFB69', 'uniFBAF'] -> uni064A067906D2.liga.init.medi.fina
['uniFBFE', 'uniFBFF', 'uniFBAF'] -> uni064A064A06D2.liga.init.medi.fina
['uniFBFE', 'uniFE8C', 'uniFBAF'] -> uni064A062606D2.liga.init.medi.fina
['uniFBFE', 'uniFE92', 'uniFBAF'] -> uni064A062806D2.liga.init.medi.fina

In [82]:
zah_glyph = cmap.get(ord("ظ"))
print("ظ glyph:", zah_glyph)

ظ glyph: uni0638

In [83]:
from fontTools.ttLib import TTFont

FONT_PATH = r"C:\Users\ammar\OneDrive\Desktop\largelisaanmodel\Kanz-al-Marjaan-Regular.ttf"

font = TTFont(FONT_PATH)

# Build unicode -> glyph name mapping
cmap = {}
for table in font["cmap"].tables:
    cmap.update(table.cmap)

# Show all glyph names related to ظ and its presentation forms
chars = [
    "ظ",
    "\uFEC5",  # ARABIC LETTER ZAH ISOLATED FORM
    "\uFEC6",  # FINAL
    "\uFEC7",  # INITIAL
    "\uFEC8",  # MEDIAL
]

for ch in chars:
    cp = ord(ch)
    print(
        repr(ch),
        f"U+{cp:04X}",
        "->",
        cmap.get(cp)
    )

'ظ' U+0638 -> uni0638
'ﻅ' U+FEC5 -> None
'ﻆ' U+FEC6 -> uniFEC6
'ﻇ' U+FEC7 -> uniFEC7
'ﻈ' U+FEC8 -> uniFEC8

In [84]:
gsub = font["GSUB"].table

for i, lookup in enumerate(gsub.LookupList.Lookup):
    print(
        "Lookup",
        i,
        "Type:",
        lookup.LookupType,
        "Subtables:",
        len(lookup.SubTable)
    )

Lookup 0 Type: 7 Subtables: 1
Lookup 1 Type: 7 Subtables: 1
Lookup 2 Type: 1 Subtables: 1
Lookup 3 Type: 1 Subtables: 1
Lookup 4 Type: 1 Subtables: 1
Lookup 5 Type: 1 Subtables: 1
Lookup 6 Type: 1 Subtables: 1
Lookup 7 Type: 4 Subtables: 1
Lookup 8 Type: 1 Subtables: 1
Lookup 9 Type: 1 Subtables: 1
Lookup 10 Type: 6 Subtables: 1
Lookup 11 Type: 6 Subtables: 1
Lookup 12 Type: 6 Subtables: 3
Lookup 13 Type: 6 Subtables: 7
Lookup 14 Type: 4 Subtables: 1
Lookup 15 Type: 4 Subtables: 1
Lookup 16 Type: 4 Subtables: 1
Lookup 17 Type: 6 Subtables: 5
Lookup 18 Type: 6 Subtables: 3
Lookup 19 Type: 6 Subtables: 1
Lookup 20 Type: 6 Subtables: 2
Lookup 21 Type: 4 Subtables: 1
Lookup 22 Type: 6 Subtables: 2
Lookup 23 Type: 4 Subtables: 1
Lookup 24 Type: 4 Subtables: 1
Lookup 25 Type: 4 Subtables: 1
Lookup 26 Type: 4 Subtables: 1
Lookup 27 Type: 4 Subtables: 1
Lookup 28 Type: 4 Subtables: 1
Lookup 29 Type: 4 Subtables: 1
Lookup 30 Type: 4 Subtables: 1
Lookup 31 Type: 4 Subtables: 1
Lookup 32 Type: 4 Subtables: 1
Lookup 33 Type: 4 Subtables: 1
Lookup 34 Type: 4 Subtables: 1
Lookup 35 Type: 4 Subtables: 1
Lookup 36 Type: 6 Subtables: 7
Lookup 37 Type: 4 Subtables: 1
Lookup 38 Type: 4 Subtables: 1
Lookup 39 Type: 4 Subtables: 1
Lookup 40 Type: 6 Subtables: 1
Lookup 41 Type: 6 Subtables: 1
Lookup 42 Type: 6 Subtables: 1
Lookup 43 Type: 6 Subtables: 12
Lookup 44 Type: 6 Subtables: 1
Lookup 45 Type: 1 Subtables: 1
Lookup 46 Type: 4 Subtables: 1

In [85]:
target_glyphs = {
    glyph
    for cp, glyph in cmap.items()
    if cp in [
        ord("ظ"),
        0xFEC5,
        0xFEC6,
        0xFEC7,
        0xFEC8,
    ]
    and glyph is not None
}

print("Target glyphs:", target_glyphs)

Target glyphs: {'uniFEC8', 'uniFEC7', 'uniFEC6', 'uni0638'}

In [86]:
for lookup_index, lookup in enumerate(gsub.LookupList.Lookup):

    print(f"\n--- Lookup {lookup_index}, type {lookup.LookupType} ---")

    for sub_index, subtable in enumerate(lookup.SubTable):

        text = repr(subtable)

        if any(glyph in text for glyph in target_glyphs):
            print(
                f"Matched in lookup {lookup_index}, "
                f"subtable {sub_index}"
            )

            print(subtable)

--- Lookup 0, type 7 ---

--- Lookup 1, type 7 ---

--- Lookup 2, type 1 ---

--- Lookup 3, type 1 ---

--- Lookup 4, type 1 ---

--- Lookup 5, type 1 ---

--- Lookup 6, type 1 ---

--- Lookup 7, type 4 ---

--- Lookup 8, type 1 ---

--- Lookup 9, type 1 ---

--- Lookup 10, type 6 ---

--- Lookup 11, type 6 ---

--- Lookup 12, type 6 ---

--- Lookup 13, type 6 ---

--- Lookup 14, type 4 ---

--- Lookup 15, type 4 ---

--- Lookup 16, type 4 ---

--- Lookup 17, type 6 ---

--- Lookup 18, type 6 ---

--- Lookup 19, type 6 ---

--- Lookup 20, type 6 ---

--- Lookup 21, type 4 ---

--- Lookup 22, type 6 ---

--- Lookup 23, type 4 ---

--- Lookup 24, type 4 ---

--- Lookup 25, type 4 ---

--- Lookup 26, type 4 ---

--- Lookup 27, type 4 ---

--- Lookup 28, type 4 ---

--- Lookup 29, type 4 ---

--- Lookup 30, type 4 ---

--- Lookup 31, type 4 ---

--- Lookup 32, type 4 ---

--- Lookup 33, type 4 ---

--- Lookup 34, type 4 ---

--- Lookup 35, type 4 ---

--- Lookup 36, type 6 ---

--- Lookup 37, type 4 ---

--- Lookup 38, type 4 ---

--- Lookup 39, type 4 ---

--- Lookup 40, type 6 ---

--- Lookup 41, type 6 ---

--- Lookup 42, type 6 ---

--- Lookup 43, type 6 ---

--- Lookup 44, type 6 ---

--- Lookup 45, type 1 ---

--- Lookup 46, type 4 ---

In [87]:
font.saveXML(
    "kanz_gsub.xml",
    tables=["GSUB"]
)

print("Saved kanz_gsub.xml")

Saved kanz_gsub.xml

In [88]:
for cp in [0xFEC5, 0xFEC6, 0xFEC7, 0xFEC8]:
    print(hex(cp), cmap.get(cp))

0xfec5 None
0xfec6 uniFEC6
0xfec7 uniFEC7
0xfec8 uniFEC8

In [89]:
text = "مظظوٹي"

import unicodedata

import unicodedata

s = "\uFEC8\uFEC8"

for ch in s:
    print(
        repr(ch),
        f"U+{ord(ch):04X}",
        unicodedata.name(ch)
    )

'ﻈ' U+FEC8 ARABIC LETTER ZAH MEDIAL FORM
'ﻈ' U+FEC8 ARABIC LETTER ZAH MEDIAL FORM

In [90]:
for ch in ["ظ", "ﻅ", "ﻆ", "ﻇ", "ﻈ"]:
    print(
        repr(ch),
        f"U+{ord(ch):04X}",
        unicodedata.name(ch, "UNKNOWN"),
        "->",
        cmap.get(ord(ch))
    )

'ظ' U+0638 ARABIC LETTER ZAH -> uni0638
'ﻅ' U+FEC5 ARABIC LETTER ZAH ISOLATED FORM -> None
'ﻆ' U+FEC6 ARABIC LETTER ZAH FINAL FORM -> uniFEC6
'ﻇ' U+FEC7 ARABIC LETTER ZAH INITIAL FORM -> uniFEC7
'ﻈ' U+FEC8 ARABIC LETTER ZAH MEDIAL FORM -> uniFEC8

In [91]:
def check_missing_images(df):
    return df[~df["full_image_path"].apply(Path.exists)]


for name, df in [
    ("TRAIN", train_df),
    ("VAL", val_df),
    ("TEST", test_df)
]:
    missing = check_missing_images(df)

    print(
        name,
        "missing:",
        len(missing),
        "/",
        len(df)
    )

    if len(missing):
        display(missing[["image", "full_image_path"]].head(20))

TRAIN missing: 0 / 3955
VAL missing: 0 / 465
TEST missing: 0 / 234

In [92]:
def verify_images(df):
    bad_images = []

    for i, row in df.iterrows():
        path = row["full_image_path"]

        try:
            with Image.open(path) as img:
                img.verify()

        except Exception as e:
            bad_images.append({
                "image": row["image"],
                "error": str(e)
            })

    return pd.DataFrame(bad_images)


bad_train = verify_images(train_df)
bad_val   = verify_images(val_df)
bad_test  = verify_images(test_df)

print("Bad train images:", len(bad_train))
print("Bad val images  :", len(bad_val))
print("Bad test images :", len(bad_test))

Bad train images: 0
Bad val images  : 0
Bad test images : 0

In [93]:
# ============================================================
# KANZ-SPECIFIC CUSTOM CHARACTER MAPPINGS
# Must run BEFORE NFKC normalization
# ============================================================
CUSTOM_KANZ_MAP = {
    "ظظ": "\uE001",
}

# Verify mapping
for source, target in CUSTOM_KANZ_MAP.items():
    print(
        "Source:",
        repr(source),
        [f"U+{ord(c):04X}" for c in source],
        "→ Target:",
        repr(target),
        f"U+{ord(target):04X}"
    )

Source: 'ظظ' ['U+0638', 'U+0638'] → Target: '\ue001' U+E001

In [94]:
all_df = pd.concat(
    [train_df, val_df, test_df],
    ignore_index=True
)

character_counts = Counter()

for text in all_df["text_original"]:
    character_counts.update(text)


character_report = []

for char, count in character_counts.items():

    character_report.append({
        "character": char,
        "unicode": f"U+{ord(char):04X}",
        "name": unicodedata.name(char, "UNKNOWN"),
        "count": count
    })


char_df = pd.DataFrame(character_report)

char_df = char_df.sort_values(
    "count",
    ascending=False
).reset_index(drop=True)

print("Unique characters:", len(char_df))

display(char_df.head(100))

Unique characters: 161

   character unicode                            name  count
0             U+0020                           SPACE  40289
1          ا  U+0627              ARABIC LETTER ALEF  22191
2          ي  U+064A               ARABIC LETTER YEH  13191
3          ن  U+0646              ARABIC LETTER NOON  11229
4          و  U+0648               ARABIC LETTER WAW   9605
..       ...     ...                             ...    ...
95         ﻨ  U+FEE8  ARABIC LETTER NOON MEDIAL FORM     29
96         d  U+0064            LATIN SMALL LETTER D     28
97         h  U+0068            LATIN SMALL LETTER H     26
98         ﻔ  U+FED4   ARABIC LETTER FEH MEDIAL FORM     25
99         2  U+0032                       DIGIT TWO     25

[100 rows x 4 columns]

In [95]:
def is_presentation_form(char):

    cp = ord(char)

    return (
        0xFB50 <= cp <= 0xFDFF or
        0xFE70 <= cp <= 0xFEFF
    )


presentation_chars = char_df[
    char_df["character"].apply(is_presentation_form)
]

print(
    "Unique Arabic Presentation Form characters:",
    len(presentation_chars)
)

display(presentation_chars)

Unique Arabic Presentation Form characters: 33

    character unicode                                           name  count
30          ﺎ  U+FE8E                  ARABIC LETTER ALEF FINAL FORM    992
37          ﻧ  U+FEE7                ARABIC LETTER NOON INITIAL FORM    725
38          ﻬ  U+FEEC                  ARABIC LETTER HEH MEDIAL FORM    724
42          ﻛ  U+FEDB                 ARABIC LETTER KAF INITIAL FORM    468
44          ﺗ  U+FE97                 ARABIC LETTER TEH INITIAL FORM    450
45          ﻪ  U+FEEA                   ARABIC LETTER HEH FINAL FORM    446
48          ﻲ  U+FEF2                   ARABIC LETTER YEH FINAL FORM    325
56          ﺟ  U+FE9F                ARABIC LETTER JEEM INITIAL FORM    219
58          ﺑ  U+FE91                 ARABIC LETTER BEH INITIAL FORM    190
68          ﻢ  U+FEE2                  ARABIC LETTER MEEM FINAL FORM    102
69          ﻤ  U+FEE4                 ARABIC LETTER MEEM MEDIAL FORM     99
78          ﻇ  U+FEC7                 ARABIC LETTER ZAH INITIAL FORM     55
82          ﻋ  U+FECB                 ARABIC LETTER AIN INITIAL FORM     48
90          ﺘ  U+FE98                  ARABIC LETTER TEH MEDIAL FORM     34
92          ﻘ  U+FED8                  ARABIC LETTER QAF MEDIAL FORM     31
95          ﻨ  U+FEE8                 ARABIC LETTER NOON MEDIAL FORM     29
98          ﻔ  U+FED4                  ARABIC LETTER FEH MEDIAL FORM     25
100         ﺸ  U+FEB8                ARABIC LETTER SHEEN MEDIAL FORM     23
102         ﺧ  U+FEA7                ARABIC LETTER KHAH INITIAL FORM     22
103         ﺴ  U+FEB4                 ARABIC LETTER SEEN MEDIAL FORM     22
109         ﻃ  U+FEC3                 ARABIC LETTER TAH INITIAL FORM     16
111         ﻏ  U+FECF               ARABIC LETTER GHAIN INITIAL FORM     15
112         ﺔ  U+FE94           ARABIC LETTER TEH MARBUTA FINAL FORM     15
118         ﺠ  U+FEA0                 ARABIC LETTER JEEM MEDIAL FORM     11
119         ﻟ  U+FEDF                 ARABIC LETTER LAM INITIAL FORM     10
121         ﺛ  U+FE9B                ARABIC LETTER THEH INITIAL FORM      8
122         ﺣ  U+FEA3                 ARABIC LETTER HAH INITIAL FORM      8
127         ﺊ  U+FE8A  ARABIC LETTER YEH WITH HAMZA ABOVE FINAL FORM      5
133         ﺳ  U+FEB3                ARABIC LETTER SEEN INITIAL FORM      5
140         ﻼ  U+FEFC       ARABIC LIGATURE LAM WITH ALEF FINAL FORM      4
147         ﻣ  U+FEE3                ARABIC LETTER MEEM INITIAL FORM      2
150         ﺨ  U+FEA8                 ARABIC LETTER KHAH MEDIAL FORM      1
156         ﺷ  U+FEB7               ARABIC LETTER SHEEN INITIAL FORM      1

In [96]:
CUSTOM_KANZ_MAP = {
    "ظظ": "\uE001",
}

def apply_kanz_map(text):
    for source, target in CUSTOM_KANZ_MAP.items():
        text = text.replace(source, target)
    return text


def normalize_text(text):

    # 1. Convert English digits to Arabic-Indic digits
    text = text.translate(ENGLISH_TO_ARABIC_DIGITS)

    # 2. Apply Kanz-specific mappings before normalization
    text = apply_kanz_map(text)

    # 3. Normalize Arabic presentation forms
    text = unicodedata.normalize("NFKC", text)

    # 4. Apply Kanz mapping again in case NFKC creates the sequence
    text = apply_kanz_map(text)

    # 5. Clean whitespace
    text = " ".join(text.split())

    return text

changed_examples = []

for _, row in all_df.iterrows():

    original = row["text_original"]
    normalized = normalize_text(original)

    if original != normalized:

        changed_examples.append({
            "image": row["image"],
            "original": original,
            "normalized": normalized
        })


changed_df = pd.DataFrame(changed_examples)

print(
    "Labels affected by NFKC:",
    len(changed_df),
    "/",
    len(all_df)
)

display(changed_df.head(50))

Labels affected by NFKC: 1310 / 4654

,image,original,normalized
0,dataset/images/train_000003_v01.png,ﻛﻪ ﺟﻬ ني معنى پاك ني ؛،,كه جه ني معنى پاك ني ؛،
1,dataset/images/train_000005_v01.png,ﺑﻬلا ايم كيم ﻧﻬ هوئي!,بهلا ايم كيم نه هوئي!
2,dataset/images/train_000010_v01.png,ﺟﻬ هر طرح سي پاك ؛،,جه هر طرح سي پاك ؛،
3,dataset/images/train_000027_v01.png,طهارة ني هداة كرام يه گهﻧﺎ} تفسير سي -detail -...,طهارة ني هداة كرام يه گهنا} تفسير سي -detail -...
4,dataset/images/train_000028_v01.png,ام سلمة كظظے ؛,ام سلمة كے ؛
5,dataset/images/train_000032_v01.png,يه مولانا عبد علي سيف الدين يه عجب شان سي اْپن...,يه مولانا عبد علي سيف الدين يه عجب شان سي اْپن...
6,dataset/images/train_000036_v01.png,ايك پالي ني معنى چار ﻛﻪوبلا،,ايك پالي ني معنى چار كهوبلا،
7,dataset/images/train_000043_v01.png,اْ جنگلے بياﺑﺎں ما أيك} سهارا حسين هﺗﺎ،,اْ جنگلے بياباں ما أيك} سهارا حسين هتا،
8,dataset/images/train_000050_v01.png,6 ازالة المدرسة السلحدار الابتدائية,٦ ازالة المدرسة السلحدار الابتدائية
9,dataset/images/train_000052_v01.png,يه پوتانے أيك گهرٌي بهي اهنا مستحق نه سمجها بل...,يه پوتانے أيك گهرٌي بهي اهنا مستحق نه سمجها بل...
10,dataset/images/train_000053_v01.png,اهني ﺧﻲر خواﻬﻲ كرے،,اهني خير خواهي كرے،
11,dataset/images/train_000054_v01.png,انے 8 ورس لگن اْپ رسول االله نا ساتهے انے مولا...,انے ٨ ورس لگن اْپ رسول االله نا ساتهے انے مولا...
12,dataset/images/train_000056_v01.png,چوكهّا كپرٌا هوئي اْم نوا} لاگے اهوا كپرٌا پظظنے،,چوكهّا كپرٌا هوئي اْم نوا} لاگے اهوا كپرٌا پنے،
13,dataset/images/train_000059_v01.png,كيم ﻛﻪ امام نو غسل ؛،,كيم كه امام نو غسل ؛،
14,dataset/images/train_000064_v01.png,سيﻛﻪاؤﺗﺎ تو اهﻧﺎ سي يه عمل ني كتني أﻬﻢية ؛,سيكهاؤتا تو اهنا سي يه عمل ني كتني أهمية ؛
15,dataset/images/train_000068_v01.png,ﻧﺎﻛﻪے انے ﺑﺎهر پدهارے ﺗﺎرے يه وات ميں يه جاني ...,ناكهے انے باهر پدهارے تارے يه وات ميں يه جاني ...
16,dataset/images/train_000073_v01.png,تو 69 مغفرة تميں سنو كئي مغفرةﻛﻪ ﺟﻬ ﻧﺎ سبب خدا...,تو ٦٩ مغفرة تميں سنو كئي مغفرةكه جه نا سبب خدا...
17,dataset/images/train_000076_v01.png,ﺟﻬ نے رزا ﺗﻬائي ﺗﻬ} اْوے،,جه نے رزا تهائي ته} اْوے،
18,dataset/images/train_000077_v01.png,هوے ﺟﻬ سخت لوگو هﺗﺎ ﻛﻪ ﺟﻬ سامنے چرٌﻬﻲنے اْوے ﻛ...,هوے جه سخت لوگو هتا كه جه سامنے چرٌهينے اْوے ك...
19,dataset/images/train_000078_v01.png,زيادة بلاء كوﻧﺎ اوپر اْوے دنيا ما ﻛﻪ ﺟﻬ رحمان ...,زيادة بلاء كونا اوپر اْوے دنيا ما كه جه رحمان ...
20,dataset/images/train_000081_v01.png,مثلا مولى ايم فرماوے ﻛﻪ دارﻬﻲ برابر راﻛﻪو،,مثلا مولى ايم فرماوے كه دارهي برابر راكهو،
21,dataset/images/train_000087_v01.png,منے ﺧﻲال ايم ﺗﻬيو ﻛﻪ فاﻃﻤة نو مكان ؛,منے خيال ايم تهيو كه فاطمة نو مكان ؛
22,dataset/images/train_000096_v01.png,ﻛﻪ:,كه:
23,dataset/images/train_000098_v01.png,ته بعد وه دهاكنو هتايو تو 10 ميٹر نو كهدّو هتو...,ته بعد وه دهاكنو هتايو تو ١٠ ميٹر نو كهدّو هتو...
24,dataset/images/train_000104_v01.png,ٹوپي پظظنے،,ٹوپي پنے،
25,dataset/images/train_000105_v01.png,سگلا ني غرض يه} ﻛﻪ اْ دعوة ﻬﻢيں مٹاوي ﻧﺎﻛﻪيےس،,سگلا ني غرض يه} كه اْ دعوة هميں مٹاوي ناكهيےس،
26,dataset/images/train_000113_v01.png,cheque نا اوپر كتنا بهي zero لگاؤ مگر جظظاں لگ...,cheque نا اوپر كتنا بهي zero لگاؤ مگر جاں لگ ...
27,dataset/images/train_000115_v01.png,تو فاﻃﻤة گهنٹي پهراوﺗﺎ هےس،,تو فاطمة گهنٹي پهراوتا هےس،
28,dataset/images/train_000118_v01.png,امام ﻧﺎ مظهر،,امام نا مظهر،
29,dataset/images/train_000119_v01.png,اﻬﻢا أيك رواية ذكر كريئے – كوني رواية ﻛﻪ,اهما أيك رواية ذكر كريئے – كوني رواية كه
30,dataset/images/train_000120_v01.png,ﺘﻤﺎرا سگلا ني ﻛﻪيتي ما گهني برﻛﺔ اْپجو،,تمارا سگلا ني كهيتي ما گهني بركة اْپجو،
31,dataset/images/train_000123_v01.png,ﺟﻬ دن سي اْپ مولى يه اْ مثل فرمايو ﺗﻬ} دن سي د...,جه دن سي اْپ مولى يه اْ مثل فرمايو ته} دن سي د...
32,dataset/images/train_000126_v01.png,المجلس الثاني 1437 هـ,المجلس الثاني ١٤٣٧ هـ
33,dataset/images/train_000132_v01.png,اهنے بيان كرﺗﺎ هوا 16 امام – امام حسين الحاكم ...,اهنے بيان كرتا هوا ١٦ امام – امام حسين الحاكم ...
34,dataset/images/train_000134_v01.png,ﻛﻪ شيعة .,كه شيعة .
35,dataset/images/train_000135_v01.png,ايم شاكلة ما تميں يه سوں پوچهو چهو كه اْپ سوں ...,ايم شاكلة ما تميں يه سوں پوچهو چهو كه اْپ سوں ...
36,dataset/images/train_000136_v01.png,تو هوے كتناك لوگو سوں كظظے ؛,تو هوے كتناك لوگو سوں كے ؛
37,dataset/images/train_000139_v01.png,دنيا ني هوئي كه دين ني اميد هوئي يه سگلي} تمام...,دنيا ني هوئي كه دين ني اميد هوئي يه سگلي} تمام...
38,dataset/images/train_000140_v01.png,كرتا دون ايم خيال كرے كه پرٌوسي ؛نظظيں بلاويئے...,كرتا دون ايم خيال كرے كه پرٌوسي ؛نيں بلاويئے ...
39,dataset/images/train_000141_v01.png,اے گﻧﺎهو سي استغفار كرﻧﺎر لوگو!,اے گناهو سي استغفار كرنار لوگو!
40,dataset/images/train_000147_v01.png,يا من لم يؤاخذ ﺑﺎلجريرة،,يا من لم يؤاخذ بالجريرة،
41,dataset/images/train_000150_v01.png,ﻛﻪ ﺟﻬ انسان ني اهوي حالة كري دے ؛,كه جه انسان ني اهوي حالة كري دے ؛
42,dataset/images/train_000151_v01.png,صاف كپرٌا پظظنے،,صاف كپرٌا پنے،
43,dataset/images/train_000152_v01.png,يه مولى نے امام ني خدمة ما گهني مصيبتو انے محن...,يه مولى نے امام ني خدمة ما گهني مصيبتو انے محن...
44,dataset/images/train_000165_v01.png,ايم نظظيں مگر إنسانية نو حال ؛,ايم نيں مگر إنسانية نو حال ؛
45,dataset/images/train_000167_v01.png,سيدﻧﺎ عبد القادر ﻧﺠﻤ الدين- تميں سگلا ويپار كر...,سيدنا عبد القادر نجم الدين- تميں سگلا ويپار كر...
46,dataset/images/train_000175_v01.png,ﻛﻪ ﺟﻬ روحاني طبيب ؛،,كه جه روحاني طبيب ؛،
47,dataset/images/train_000176_v01.png,دعوة ني بظظاء انے بظظجة؛،,دعوة ني باء انے بجة؛،
48,dataset/images/train_000178_v01.png,دور ﺗﻬئي .,دور تهئي .
49,dataset/images/train_000184_v01.png,تاكه پانچسو اوقية ورسو ما جمع تهئي … برٌهيا زي...,تاكه پانچسو اوقية ورسو ما جمع تهئي ... برٌهيا ...

In [97]:
SPECIAL_SEQUENCE = "\u0638\u0638"   # ظظ

print("Searching for:", repr(SPECIAL_SEQUENCE))
print("Code points:", [f"U+{ord(c):04X}" for c in SPECIAL_SEQUENCE])

matches = all_df[
    all_df["text_original"].str.contains(
        SPECIAL_SEQUENCE,
        regex=False,
        na=False
    )
]

print("Labels containing special Kanz sequence:", len(matches))

display(
    matches[
        ["split", "image", "text_original"]
    ].head(30)
)

Searching for: 'ظظ'
Code points: ['U+0638', 'U+0638']
Labels containing special Kanz sequence: 403

,split,image,text_original
27,train,dataset/images/train_000028_v01.png,ام سلمة كظظے ؛
31,train,dataset/images/train_000032_v01.png,يه مولانا عبد علي سيف الدين يه عجب شان سي اْپن...
51,train,dataset/images/train_000052_v01.png,يه پوتانے أيك گهرٌي بهي اهنا مستحق نه سمجها بل...
53,train,dataset/images/train_000054_v01.png,انے 8 ورس لگن اْپ رسول االله نا ساتهے انے مولا...
55,train,dataset/images/train_000056_v01.png,چوكهّا كپرٌا هوئي اْم نوا} لاگے اهوا كپرٌا پظظنے،
103,train,dataset/images/train_000104_v01.png,ٹوپي پظظنے،
112,train,dataset/images/train_000113_v01.png,cheque نا اوپر كتنا بهي zero لگاؤ مگر جظظاں لگ...
134,train,dataset/images/train_000135_v01.png,ايم شاكلة ما تميں يه سوں پوچهو چهو كه اْپ سوں ...
135,train,dataset/images/train_000136_v01.png,تو هوے كتناك لوگو سوں كظظے ؛
138,train,dataset/images/train_000139_v01.png,دنيا ني هوئي كه دين ني اميد هوئي يه سگلي} تمام...
139,train,dataset/images/train_000140_v01.png,كرتا دون ايم خيال كرے كه پرٌوسي ؛نظظيں بلاويئے...
150,train,dataset/images/train_000151_v01.png,صاف كپرٌا پظظنے،
151,train,dataset/images/train_000152_v01.png,يه مولى نے امام ني خدمة ما گهني مصيبتو انے محن...
164,train,dataset/images/train_000165_v01.png,ايم نظظيں مگر إنسانية نو حال ؛
175,train,dataset/images/train_000176_v01.png,دعوة ني بظظاء انے بظظجة؛،
190,train,dataset/images/train_000191_v01.png,اْه اْه اْه كظظي نے نعره بلند كرنار كري ديدا
191,train,dataset/images/train_000192_v01.png,تو منے فاطمة ني شادي ياد اْوي كه اهما كوئي نثا...
200,train,dataset/images/train_000201_v01.png,تو وه دكرو سوں كظظے ؛
205,train,dataset/images/train_000206_v01.png,جو نظظيں اْپو تو ،
216,train,dataset/images/train_000217_v01.png,ﻛﻪ اْپني شظظزاديو دﺸﻢنو ﻧﺎ نرغه ما كُهلے سر ؛،
219,train,dataset/images/train_000220_v01.png,تو لعين ثاني كظظے ؛
221,train,dataset/images/train_000222_v01.png,كه ولي االله كوئي نے اونچا كرے يا كوئي نے نيچا...
222,train,dataset/images/train_000223_v01.png,"""ولو ردوا لعادوا لما نظظوا عنه""،"
225,train,dataset/images/train_000226_v01.png,سفينة كوئي دن دوبےس نظظيں،
227,train,dataset/images/train_000228_v01.png,كوئي ﺑﻬي اهوي جگه ﺑﺎﻘﻲ نﺗﻬي ﻛﻪ جظظاں خون ﻧﺎ لا...
238,train,dataset/images/train_000239_v01.png,خلق في اقطار افلاكظظا* فالاوهام فيـه تواقع الت...
256,train,dataset/images/train_000257_v01.png,يظظاں ﺑﻬي كتروو ﻧﻬ جوئيے،
258,train,dataset/images/train_000259_v01.png,اْپ سوں كظظسو ؟
261,train,dataset/images/train_000262_v01.png,اْج پظظلي مجلس ؛
286,train,dataset/images/train_000287_v01.png,اْدم اْ دور ﻧﺎ پظظلا نبي ؛

In [98]:
important_chars = [
    "پ",
    "چ",
    "ک",
    "گ",
    "ں",
    "ھ",
    "ہ",
    "ی",
    "ے",
    "ٹ",
    "ڈ",
    "ڑ"
]


print("CHAR | BEFORE | AFTER | SAME?")
print("-" * 50)

for char in important_chars:

    normalized = normalize_text(char)

    print(
        repr(char),
        f"U+{ord(char):04X}",
        "→",
        repr(normalized),
        [f"U+{ord(c):04X}" for c in normalized],
        char == normalized
    )

CHAR | BEFORE | AFTER | SAME?
--------------------------------------------------
'پ' U+067E → 'پ' ['U+067E'] True
'چ' U+0686 → 'چ' ['U+0686'] True
'ک' U+06A9 → 'ک' ['U+06A9'] True
'گ' U+06AF → 'گ' ['U+06AF'] True
'ں' U+06BA → 'ں' ['U+06BA'] True
'ھ' U+06BE → 'ھ' ['U+06BE'] True
'ہ' U+06C1 → 'ہ' ['U+06C1'] True
'ی' U+06CC → 'ی' ['U+06CC'] True
'ے' U+06D2 → 'ے' ['U+06D2'] True
'ٹ' U+0679 → 'ٹ' ['U+0679'] True
'ڈ' U+0688 → 'ڈ' ['U+0688'] True
'ڑ' U+0691 → 'ڑ' ['U+0691'] True

In [100]:
for df in [train_df, val_df, test_df]:
    df["text_normalized"] = df["text_original"].apply(normalize_text)
    df["text_final"] = df["text_normalized"]

In [101]:
ENGLISH_DIGITS = "0123456789"
ARABIC_DIGITS = "٠١٢٣٤٥٦٧٨٩"

for name, df in [
    ("train", train_df),
    ("val", val_df),
    ("test", test_df)
]:
    english_rows = df["text_final"].apply(
        lambda x: any(c in ENGLISH_DIGITS for c in x)
    ).sum()

    arabic_rows = df["text_final"].apply(
        lambda x: any(c in ARABIC_DIGITS for c in x)
    ).sum()

    print(
        name,
        "| English numeral rows remaining:", english_rows,
        "| Arabic numeral rows:", arabic_rows
    )

train | English numeral rows remaining: 0 | Arabic numeral rows: 78
val | English numeral rows remaining: 0 | Arabic numeral rows: 17
test | English numeral rows remaining: 0 | Arabic numeral rows: 8

In [102]:
display(
    train_df[
        train_df["text_original"]
        != train_df["text_normalized"]
    ][
        [
            "image",
            "text_original",
            "text_normalized"
        ]
    ].head(30)
)

,image,text_original,text_normalized
2,dataset/images/train_000003_v01.png,ﻛﻪ ﺟﻬ ني معنى پاك ني ؛،,كه جه ني معنى پاك ني ؛،
4,dataset/images/train_000005_v01.png,ﺑﻬلا ايم كيم ﻧﻬ هوئي!,بهلا ايم كيم نه هوئي!
9,dataset/images/train_000010_v01.png,ﺟﻬ هر طرح سي پاك ؛،,جه هر طرح سي پاك ؛،
26,dataset/images/train_000027_v01.png,طهارة ني هداة كرام يه گهﻧﺎ} تفسير سي -detail -...,طهارة ني هداة كرام يه گهنا} تفسير سي -detail -...
27,dataset/images/train_000028_v01.png,ام سلمة كظظے ؛,ام سلمة كے ؛
31,dataset/images/train_000032_v01.png,يه مولانا عبد علي سيف الدين يه عجب شان سي اْپن...,يه مولانا عبد علي سيف الدين يه عجب شان سي اْپن...
35,dataset/images/train_000036_v01.png,ايك پالي ني معنى چار ﻛﻪوبلا،,ايك پالي ني معنى چار كهوبلا،
42,dataset/images/train_000043_v01.png,اْ جنگلے بياﺑﺎں ما أيك} سهارا حسين هﺗﺎ،,اْ جنگلے بياباں ما أيك} سهارا حسين هتا،
49,dataset/images/train_000050_v01.png,6 ازالة المدرسة السلحدار الابتدائية,٦ ازالة المدرسة السلحدار الابتدائية
51,dataset/images/train_000052_v01.png,يه پوتانے أيك گهرٌي بهي اهنا مستحق نه سمجها بل...,يه پوتانے أيك گهرٌي بهي اهنا مستحق نه سمجها بل...
52,dataset/images/train_000053_v01.png,اهني ﺧﻲر خواﻬﻲ كرے،,اهني خير خواهي كرے،
53,dataset/images/train_000054_v01.png,انے 8 ورس لگن اْپ رسول االله نا ساتهے انے مولا...,انے ٨ ورس لگن اْپ رسول االله نا ساتهے انے مولا...
55,dataset/images/train_000056_v01.png,چوكهّا كپرٌا هوئي اْم نوا} لاگے اهوا كپرٌا پظظنے،,چوكهّا كپرٌا هوئي اْم نوا} لاگے اهوا كپرٌا پنے،
58,dataset/images/train_000059_v01.png,كيم ﻛﻪ امام نو غسل ؛،,كيم كه امام نو غسل ؛،
63,dataset/images/train_000064_v01.png,سيﻛﻪاؤﺗﺎ تو اهﻧﺎ سي يه عمل ني كتني أﻬﻢية ؛,سيكهاؤتا تو اهنا سي يه عمل ني كتني أهمية ؛
67,dataset/images/train_000068_v01.png,ﻧﺎﻛﻪے انے ﺑﺎهر پدهارے ﺗﺎرے يه وات ميں يه جاني ...,ناكهے انے باهر پدهارے تارے يه وات ميں يه جاني ...
72,dataset/images/train_000073_v01.png,تو 69 مغفرة تميں سنو كئي مغفرةﻛﻪ ﺟﻬ ﻧﺎ سبب خدا...,تو ٦٩ مغفرة تميں سنو كئي مغفرةكه جه نا سبب خدا...
75,dataset/images/train_000076_v01.png,ﺟﻬ نے رزا ﺗﻬائي ﺗﻬ} اْوے،,جه نے رزا تهائي ته} اْوے،
76,dataset/images/train_000077_v01.png,هوے ﺟﻬ سخت لوگو هﺗﺎ ﻛﻪ ﺟﻬ سامنے چرٌﻬﻲنے اْوے ﻛ...,هوے جه سخت لوگو هتا كه جه سامنے چرٌهينے اْوے ك...
77,dataset/images/train_000078_v01.png,زيادة بلاء كوﻧﺎ اوپر اْوے دنيا ما ﻛﻪ ﺟﻬ رحمان ...,زيادة بلاء كونا اوپر اْوے دنيا ما كه جه رحمان ...
80,dataset/images/train_000081_v01.png,مثلا مولى ايم فرماوے ﻛﻪ دارﻬﻲ برابر راﻛﻪو،,مثلا مولى ايم فرماوے كه دارهي برابر راكهو،
86,dataset/images/train_000087_v01.png,منے ﺧﻲال ايم ﺗﻬيو ﻛﻪ فاﻃﻤة نو مكان ؛,منے خيال ايم تهيو كه فاطمة نو مكان ؛
95,dataset/images/train_000096_v01.png,ﻛﻪ:,كه:
97,dataset/images/train_000098_v01.png,ته بعد وه دهاكنو هتايو تو 10 ميٹر نو كهدّو هتو...,ته بعد وه دهاكنو هتايو تو ١٠ ميٹر نو كهدّو هتو...
103,dataset/images/train_000104_v01.png,ٹوپي پظظنے،,ٹوپي پنے،
104,dataset/images/train_000105_v01.png,سگلا ني غرض يه} ﻛﻪ اْ دعوة ﻬﻢيں مٹاوي ﻧﺎﻛﻪيےس،,سگلا ني غرض يه} كه اْ دعوة هميں مٹاوي ناكهيےس،
112,dataset/images/train_000113_v01.png,cheque نا اوپر كتنا بهي zero لگاؤ مگر جظظاں لگ...,cheque نا اوپر كتنا بهي zero لگاؤ مگر جاں لگ ...
114,dataset/images/train_000115_v01.png,تو فاﻃﻤة گهنٹي پهراوﺗﺎ هےس،,تو فاطمة گهنٹي پهراوتا هےس،
117,dataset/images/train_000118_v01.png,امام ﻧﺎ مظهر،,امام نا مظهر،
118,dataset/images/train_000119_v01.png,اﻬﻢا أيك رواية ذكر كريئے – كوني رواية ﻛﻪ,اهما أيك رواية ذكر كريئے – كوني رواية كه

In [103]:
def clean_whitespace(text):

    # Convert repeated spaces/tabs/newlines
    # into a single normal space.

    return " ".join(text.split())


for df in [train_df, val_df, test_df]:

    df["text_final"] = (
        df["text_normalized"]
        .apply(clean_whitespace)
    )

In [104]:
for name, df in [
    ("train", train_df),
    ("val", val_df),
    ("test", test_df)
]:

    empty = df[
        df["text_final"].str.len() == 0
    ]

    print(name, "empty labels:", len(empty))

train empty labels: 0
val empty labels: 0
test empty labels: 0

In [105]:
all_final = pd.concat(
    [train_df, val_df, test_df],
    ignore_index=True
)

all_final["characters"] = (
    all_final["text_final"].str.len()
)

all_final["words"] = (
    all_final["text_final"]
    .apply(lambda x: len(x.split()))
)

display(
    all_final[
        ["characters", "words"]
    ].describe(
        percentiles=[
            .50,
            .75,
            .90,
            .95,
            .99
        ]
    )
)

        characters        words
count  4654.000000  4654.000000
mean     42.641169     9.656639
std      29.180382     6.444681
min       1.000000     1.000000
50%      33.000000     8.000000
75%      58.750000    13.000000
90%      96.000000    21.000000
95%     103.000000    23.000000
99%     109.000000    25.000000
max     114.000000    29.000000

In [106]:
display(
    all_final
    .sort_values(
        "characters",
        ascending=False
    )[
        [
            "image",
            "characters",
            "words",
            "text_final"
        ]
    ]
    .head(30)
)

,image,characters,words,text_final
1404,dataset/images/train_001405_v01.png,114,24,هاهنا و أخذتم حيث أخذ نبي االله و أولياء االله...
1270,dataset/images/train_001271_v01.png,112,24,أمرت بسد أبوابكم و لا فتحت باب علي بل االله أم...
553,dataset/images/train_000554_v01.png,112,27,ذلك و لكن االله فعله و إن االله أوحى إلى موسى ...
79,dataset/images/train_000080_v01.png,111,17,الحمد الله المتعالي عن الاضداد والاشباه* المخت...
2731,dataset/images/train_002732_v01.png,111,22,"كه ""يهدي االله لنوره من يشاء"" تو يه شان مولانا..."
4205,dataset/images/val_000251_v01.png,111,18,أَرْجُلَكُمْ إِلَى الْكَعْبَيْنِ فبان أن المسح...
4226,dataset/images/val_000272_v01.png,111,19,عبد االله ووليه ابو علي المنصور الامام الحاكم ...
629,dataset/images/train_000630_v01.png,111,25,االله ص بعث أبا بكر و معه براءة إلى أهل الموسم...
4578,dataset/images/test_000159_v01.png,111,27,و عن أبي جعفر ع أنه قال إن الجنة لتشتاق و يشتد...
3184,dataset/images/train_003185_v01.png,111,20,الحمد الله المحيط بكل شيـئ علمه* العظيم عن الع...
2472,dataset/images/train_002473_v01.png,111,23,ثم أمروا بعد ذلك بالمسح على الرجلين و هو قول ا...
3950,dataset/images/train_003951_v01.png,111,28,و لذلك قال أبو جعفر محمد بن علي ص و قد سئل عن ...
2286,dataset/images/train_002287_v01.png,111,25,يكن لي فيه صنع قالوا و ما ذلك يا أمير المؤمنين...
1901,dataset/images/train_001902_v01.png,111,25,آذاني فقال أمير المؤمنين علي ع لعلك أكلت ألوان...
3345,dataset/images/train_003346_v01.png,111,24,"""و روينا عن بعضهم ص أنه أمر بابتناء مخرج في ال..."
320,dataset/images/train_000321_v01.png,111,27,فقال عبد االله بن ابي و هو الذي رجع و رجع معه ...
2714,dataset/images/train_002715_v01.png,110,26,و من ترك عضوا من أعضاء الوضوء لم تكمل طهارته و...
1007,dataset/images/train_001008_v01.png,110,25,فأتى رسول االله ص فقال يا رسول االله دع لي بقد...
1206,dataset/images/train_001207_v01.png,110,20,وهذا الاعمال التي هي القول والعمل والنية تجري ...
2936,dataset/images/train_002937_v01.png,110,25,التيمم على من لم يجد الماء جعل التيمم مسحا على...
2168,dataset/images/train_002169_v01.png,110,24,و قال علي ضُمّنت لمن سمى االله على طعامه أن لا...
2310,dataset/images/train_002311_v01.png,110,24,طلحة و الزبير و عثمان و عبد الرحمن و سعد و حمز...
3055,dataset/images/train_003056_v01.png,110,24,ثم يدخل المتوضئ يديه جميعا في الاناء او يده ال...
3588,dataset/images/train_003589_v01.png,110,21,جميعا من اعلاه من منقطع الشعر من الجبهة الى ال...
4271,dataset/images/val_000317_v01.png,110,24,و قول الجماعة أن الإيمان قول و عمل بغير اعتقاد...
3252,dataset/images/train_003253_v01.png,110,23,قال كنت أنا و العباس و عثمان بن شيبة في المسجد...
3330,dataset/images/train_003331_v01.png,110,27,فيه غيرهم و إن االله أوحى إلي أن أتخذ هذا البي...
1976,dataset/images/train_001977_v01.png,110,25,و قد ذكر أبو جعفر محمد بن علي ص بيان ذلك من كت...
154,dataset/images/train_000155_v01.png,110,25,فالعجب لمن سمع هذا من رسول االله صلع فتخلف عن ...
742,dataset/images/train_000743_v01.png,110,23,قد روينا عن علي بن أبي طالب ص أن قوما سألوه فق...

In [107]:
def get_image_dimensions(path):

    try:

        with Image.open(path) as img:
            return img.width, img.height

    except:
        return None, None


dimensions = all_final[
    "full_image_path"
].apply(get_image_dimensions)


all_final["width"] = [
    d[0] for d in dimensions
]

all_final["height"] = [
    d[1] for d in dimensions
]


display(
    all_final[
        ["width", "height"]
    ].describe()
)

        width  height
count  4654.0  4654.0
mean   1800.0   230.0
std       0.0     0.0
min    1800.0   230.0
25%    1800.0   230.0
50%    1800.0   230.0
75%    1800.0   230.0
max    1800.0   230.0

In [108]:
all_final["aspect_ratio"] = (
    all_final["width"]
    /
    all_final["height"]
)


display(
    all_final[
        [
            "width",
            "height",
            "aspect_ratio"
        ]
    ].describe()
)

        width  height  aspect_ratio
count  4654.0  4654.0   4654.000000
mean   1800.0   230.0      7.826087
std       0.0     0.0      0.000000
min    1800.0   230.0      7.826087
25%    1800.0   230.0      7.826087
50%    1800.0   230.0      7.826087
75%    1800.0   230.0      7.826087
max    1800.0   230.0      7.826087

In [109]:
duplicate_text = all_final[
    all_final.duplicated(
        subset=["text_final"],
        keep=False
    )
].sort_values("text_final")


print(
    "Rows with duplicate transcription:",
    len(duplicate_text)
)

display(
    duplicate_text[
        [
            "split",
            "image",
            "text_final"
        ]
    ].head(50)
)

Rows with duplicate transcription: 2

      split                                image       text_final
823   train  dataset/images/train_000824_v01.png  اے رسول االله !
1810  train  dataset/images/train_001811_v01.png  اے رسول االله !

In [110]:
train_texts = set(train_df["text_final"])
val_texts   = set(val_df["text_final"])
test_texts  = set(test_df["text_final"])


train_val_overlap = train_texts & val_texts
train_test_overlap = train_texts & test_texts
val_test_overlap = val_texts & test_texts


print(
    "Train ↔ Val duplicate labels:",
    len(train_val_overlap)
)

print(
    "Train ↔ Test duplicate labels:",
    len(train_test_overlap)
)

print(
    "Val ↔ Test duplicate labels:",
    len(val_test_overlap)
)

Train ↔ Val duplicate labels: 0
Train ↔ Test duplicate labels: 0
Val ↔ Test duplicate labels: 0

In [111]:
OCR_PROMPT = (
    "Transcribe the text in this image exactly. "
    "Preserve the original spelling, punctuation and characters. "
    "Do not translate, explain, correct or add any text. "
    "Return only the transcription."
)

In [112]:
def create_qwen_record(row):

    return {
        "messages": [
            {
                "role": "user",
                "content": [
                    {
                        "type": "image",
                        "image": row["image"]
                    },
                    {
                        "type": "text",
                        "text": OCR_PROMPT
                    }
                ]
            },
            {
                "role": "assistant",
                "content": [
                    {
                        "type": "text",
                        "text": row["text_final"]
                    }
                ]
            }
        ]
    }

In [113]:
def write_jsonl(df, output_file):

    with open(
        output_file,
        "w",
        encoding="utf-8"
    ) as f:

        for _, row in df.iterrows():

            record = create_qwen_record(row)

            f.write(
                json.dumps(
                    record,
                    ensure_ascii=False
                )
                + "\n"
            )


write_jsonl(
    train_df,
    OUTPUT_DIR / "train.jsonl"
)

write_jsonl(
    val_df,
    OUTPUT_DIR / "val.jsonl"
)

write_jsonl(
    test_df,
    OUTPUT_DIR / "test.jsonl"
)


print("Created:")
print(OUTPUT_DIR / "train.jsonl")
print(OUTPUT_DIR / "val.jsonl")
print(OUTPUT_DIR / "test.jsonl")

Created:
C:\Users\ammar\OneDrive\Desktop\largelisaanmodel\dataset_qwen\train.jsonl
C:\Users\ammar\OneDrive\Desktop\largelisaanmodel\dataset_qwen\val.jsonl
C:\Users\ammar\OneDrive\Desktop\largelisaanmodel\dataset_qwen\test.jsonl

In [114]:
with open(
    OUTPUT_DIR / "train.jsonl",
    "r",
    encoding="utf-8"
) as f:

    sample = json.loads(
        f.readline()
    )


print(
    json.dumps(
        sample,
        ensure_ascii=False,
        indent=2
    )
)

{
  "messages": [
    {
      "role": "user",
      "content": [
        {
          "type": "image",
          "image": "dataset/images/train_000001_v01.png"
        },
        {
          "type": "text",
          "text": "Transcribe the text in this image exactly. Preserve the original spelling, punctuation and characters. Do not translate, explain, correct or add any text. Return only the transcription."
        }
      ]
    },
    {
      "role": "assistant",
      "content": [
        {
          "type": "text",
          "text": "اْپنا دل ني انے جه قران اْپنا دل پر اترا يه سگلا ني معرفة كرينے حقيقة اْپني امة خالصة اپن سگلا؛،"
        }
      ]
    }
  ]
}

In [115]:
def save_normalized_txt(df, output_file):

    with open(
        output_file,
        "w",
        encoding="utf-8"
    ) as f:

        for _, row in df.iterrows():

            f.write(
                f"{row['image']}\t"
                f"{row['text_final']}\n"
            )


save_normalized_txt(
    train_df,
    OUTPUT_DIR / "train_normalized.txt"
)

save_normalized_txt(
    val_df,
    OUTPUT_DIR / "val_normalized.txt"
)

save_normalized_txt(
    test_df,
    OUTPUT_DIR / "test_normalized.txt"
)

In [116]:
print("=" * 60)
print("QWEN DATASET PREPARATION COMPLETE")
print("=" * 60)

print()
print("Samples")
print("-------")
print("Train:", len(train_df))
print("Val:  ", len(val_df))
print("Test: ", len(test_df))

print()
print("Unicode")
print("-------")
print(
    "Original unique characters:",
    len(character_counts)
)

print(
    "Presentation form characters:",
    len(presentation_chars)
)

print(
    "Labels changed by NFKC:",
    len(changed_df)
)

print()
print("Split leakage")
print("-------------")

print(
    "Train ↔ Val:",
    len(train_val_overlap)
)

print(
    "Train ↔ Test:",
    len(train_test_overlap)
)

print(
    "Val ↔ Test:",
    len(val_test_overlap)
)

print()
print("Output")
print("------")

print(
    OUTPUT_DIR / "train.jsonl"
)

print(
    OUTPUT_DIR / "val.jsonl"
)

print(
    OUTPUT_DIR / "test.jsonl"
)

============================================================
QWEN DATASET PREPARATION COMPLETE
============================================================

Samples
-------
Train: 3955
Val:   465
Test:  234

Unicode
-------
Original unique characters: 161
Presentation form characters: 33
Labels changed by NFKC: 1310

Split leakage
-------------
Train ↔ Val: 0
Train ↔ Test: 0
Val ↔ Test: 0

Output
------
C:\Users\ammar\OneDrive\Desktop\largelisaanmodel\dataset_qwen\train.jsonl
C:\Users\ammar\OneDrive\Desktop\largelisaanmodel\dataset_qwen\val.jsonl
C:\Users\ammar\OneDrive\Desktop\largelisaanmodel\dataset_qwen\test.jsonl

In [117]:
display(
    changed_df[
        ["image", "original", "normalized"]
    ].sample(
        min(20, len(changed_df)),
        random_state=42
    )
)

,image,original,normalized
701,dataset/images/train_002563_v01.png,ﻛﻪ ﺟﻬ ﻧﺎ سي} سگلا دعائم ني حفاظة ؛,كه جه نا سي} سگلا دعائم ني حفاظة ؛
994,dataset/images/train_003586_v01.png,اْه اْ حسين ني دنيا ني سفر اْج ﺘﻤﺎم ﺗﻬئي گئي !,اْه اْ حسين ني دنيا ني سفر اْج تمام تهئي گئي !
350,dataset/images/train_001295_v01.png,ياحسين كظظي نے مأتم كرينے صراط مستقيم پر قدم ن...,ياحسين كي نے مأتم كرينے صراط مستقيم پر قدم نے...
986,dataset/images/train_003554_v01.png,مارا مولى امام الزمان جه سوجهاؤےس ته كظظيس،,مارا مولى امام الزمان جه سوجهاؤےس ته كيس،
409,dataset/images/train_001497_v01.png,ﻛﻪ جنة،,كه جنة،
917,dataset/images/train_003298_v01.png,ستر العورة كرواني أيك معنى سوں ﻛﻪ كوئي ﻧﺎ ﻋﻲب ...,ستر العورة كرواني أيك معنى سوں كه كوئي نا عيب ...
905,dataset/images/train_003254_v01.png,تو يه كﺗﺎب المصابيح ما اْپ شريعة ني ضرورة انسا...,تو يه كتاب المصابيح ما اْپ شريعة ني ضرورة انسا...
1117,dataset/images/val_000037_v01.png,هوے اْ مثل ني خبر سيدنا نے پظظنچے ؛,هوے اْ مثل ني خبر سيدنا نے پنچے ؛
1168,dataset/images/val_000231_v01.png,أے عزادارو اْج جانو چهو سوں ﺗﻬيو ارے سوں ﺗﻬيو ...,أے عزادارو اْج جانو چهو سوں تهيو ارے سوں تهيو ...
344,dataset/images/train_001268_v01.png,تمام لوگو ابن ابي الحديد كظظے ؛,تمام لوگو ابن ابي الحديد كے ؛
1216,dataset/images/val_000392_v01.png,وه شخص ني روزي نے كشاده كرجے ﺟﻬ اهﻧﺎ ﺑﻬائي ني ...,وه شخص ني روزي نے كشاده كرجے جه اهنا بهائي ني ...
1046,dataset/images/train_003763_v01.png,اپﻧﺎ ماحول ما بظظره پنو هوئي،,اپنا ماحول ما بره پنو هوئي،
231,dataset/images/train_000829_v01.png,تو صراط مستقيم ني معنى سوں ظاهر نا لوگو اهني ت...,تو صراط مستقيم ني معنى سوں ظاهر نا لوگو اهني ت...
950,dataset/images/train_003410_v01.png,سكينة نے كيم ﺴﻢﺟﻬايا هےس – ﻛﻪ بيٹا منے جاوا دو!,سكينة نے كيم سمجهايا هےس – كه بيٹا منے جاوا دو!
192,dataset/images/train_000698_v01.png,خاميو انے شك دور ﺗﻬائي,خاميو انے شك دور تهائي
739,dataset/images/train_002700_v01.png,اْپﻧﺎ منصوص انے وارث،,اْپنا منصوص انے وارث،
352,dataset/images/train_001297_v01.png,ايك موج نظظيں،,ايك موج نيں،
1062,dataset/images/train_003806_v01.png,كﺗﺎب الطهارة ما ﻛﻪ ﺟﻬ ني ذكر ﺗﻬئي اﻬﻢا سيدﻧﺎ ا...,كتاب الطهارة ما كه جه ني ذكر تهئي اهما سيدنا ا...
554,dataset/images/train_002037_v01.png,اُٹهواني طاقة نﺗﻬي،,اُٹهواني طاقة نتهي،
363,dataset/images/train_001332_v01.png,عجب خدا ﻧﺎ اپﻧﺎ اوپر احسان ؛,عجب خدا نا اپنا اوپر احسان ؛

In [118]:
for name, df in [
    ("train", train_df),
    ("val", val_df),
    ("test", test_df)
]:
    remaining = df["text_final"].str.contains(
        "ظظ",
        regex=False,
        na=False
    ).sum()

    special = df["text_final"].str.contains(
        "\uE001",
        regex=False,
        na=False
    ).sum()

    print(
        name,
        "| raw ظظ remaining:", remaining,
        "| U+E001 samples:", special
    )

train | raw ظظ remaining: 0 | U+E001 samples: 378
val | raw ظظ remaining: 0 | U+E001 samples: 45
test | raw ظظ remaining: 0 | U+E001 samples: 23

In [119]:
save_normalized_txt(
    train_df,
    OUTPUT_DIR / "train_normalized.txt"
)

save_normalized_txt(
    val_df,
    OUTPUT_DIR / "val_normalized.txt"
)

save_normalized_txt(
    test_df,
    OUTPUT_DIR / "test_normalized.txt"
)

write_jsonl(
    train_df,
    OUTPUT_DIR / "train.jsonl"
)

write_jsonl(
    val_df,
    OUTPUT_DIR / "val.jsonl"
)

write_jsonl(
    test_df,
    OUTPUT_DIR / "test.jsonl"
)

In [120]:
for name, df in [
    ("train", train_df),
    ("val", val_df),
    ("test", test_df)
]:
    print(
        name,
        "| rows:", len(df),
        "| empty:", (df["text_final"].str.len() == 0).sum(),
        "| raw ظظ:", df["text_final"].str.contains("ظظ", regex=False, na=False).sum(),
        "| U+E001:", df["text_final"].str.contains("\uE001", regex=False, na=False).sum(),
    )

train | rows: 3955 | empty: 0 | raw ظظ: 0 | U+E001: 378
val | rows: 465 | empty: 0 | raw ظظ: 0 | U+E001: 45
test | rows: 234 | empty: 0 | raw ظظ: 0 | U+E001: 23

In [121]:
import json

with open(
    OUTPUT_DIR / "train.jsonl",
    "r",
    encoding="utf-8"
) as f:
    for line in f:
        obj = json.loads(line)

        target = obj["messages"][1]["content"][0]["text"]

        if "\uE001" in target:
            print(json.dumps(obj, ensure_ascii=False, indent=2))
            print(
                "Codepoints:",
                [f"U+{ord(c):04X}" for c in target]
            )
            break

{
  "messages": [
    {
      "role": "user",
      "content": [
        {
          "type": "image",
          "image": "dataset/images/train_000028_v01.png"
        },
        {
          "type": "text",
          "text": "Transcribe the text in this image exactly. Preserve the original spelling, punctuation and characters. Do not translate, explain, correct or add any text. Return only the transcription."
        }
      ]
    },
    {
      "role": "assistant",
      "content": [
        {
          "type": "text",
          "text": "ام سلمة كے ؛"
        }
      ]
    }
  ]
}
Codepoints: ['U+0627', 'U+0645', 'U+0020', 'U+0633', 'U+0644', 'U+0645', 'U+0629', 'U+0020', 'U+0643', 'U+E001', 'U+06D2', 'U+0020', 'U+061B']

In [124]:
# Final dataset sanity checks

for name, df in [
    ("train", train_df),
    ("val", val_df),
    ("test", test_df)
]:
    raw_kanz = df["text_final"].str.contains(
        "ظظ", regex=False, na=False
    ).sum()

    special_kanz = df["text_final"].str.contains(
        "\uE001", regex=False, na=False
    ).sum()

    english_digits = df["text_final"].apply(
        lambda x: any(c in "0123456789" for c in x)
    ).sum()

    arabic_digits = df["text_final"].apply(
        lambda x: any(c in "٠١٢٣٤٥٦٧٨٩" for c in x)
    ).sum()

    empty = (df["text_final"].str.len() == 0).sum()

    print(f"\n{name.upper()}")
    print("Rows:", len(df))
    print("Empty labels:", empty)
    print("Raw ظظ remaining:", raw_kanz)
    print("U+E001 samples:", special_kanz)
    print("English numeral rows:", english_digits)
    print("Arabic numeral rows:", arabic_digits)

TRAIN
Rows: 3955
Empty labels: 0
Raw ظظ remaining: 0
U+E001 samples: 378
English numeral rows: 0
Arabic numeral rows: 78

VAL
Rows: 465
Empty labels: 0
Raw ظظ remaining: 0
U+E001 samples: 45
English numeral rows: 0
Arabic numeral rows: 17

TEST
Rows: 234
Empty labels: 0
Raw ظظ remaining: 0
U+E001 samples: 23
English numeral rows: 0
Arabic numeral rows: 8